// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AcquireCardShardArgs {
    pub time_ms: u64,
    pub data_shard: u16,
}

impl From<AcquireCardShardArgs> for super::Reducer {
    fn from(args: AcquireCardShardArgs) -> Self {
        Self::AcquireCardShard {
            time_ms: args.time_ms,
            data_shard: args.data_shard,
}
}
}

impl __sdk::InModule for AcquireCardShardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `acquire_card_shard`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait acquire_card_shard {
    /// Request that the remote module invoke the reducer `acquire_card_shard` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`acquire_card_shard:acquire_card_shard_then`] to run a callback after the reducer completes.
    fn acquire_card_shard(&self, time_ms: u64,
data_shard: u16,
) -> __sdk::Result<()> {
        self.acquire_card_shard_then(time_ms, data_shard,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `acquire_card_shard` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn acquire_card_shard_then(
        &self,
        time_ms: u64,
data_shard: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl acquire_card_shard for super::RemoteReducers {
    fn acquire_card_shard_then(
        &self,
        time_ms: u64,
data_shard: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AcquireCardShardArgs { time_ms, data_shard,  }, callback)
    }
}

