// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddCardArgs {
    pub client_time_ms: u64,
    pub soul_card_id: u32,
    pub card_key: String,
}

impl From<AddCardArgs> for super::Reducer {
    fn from(args: AddCardArgs) -> Self {
        Self::AddCard {
            client_time_ms: args.client_time_ms,
            soul_card_id: args.soul_card_id,
            card_key: args.card_key,
}
}
}

impl __sdk::InModule for AddCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_card {
    /// Request that the remote module invoke the reducer `add_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_card:add_card_then`] to run a callback after the reducer completes.
    fn add_card(&self, client_time_ms: u64,
soul_card_id: u32,
card_key: String,
) -> __sdk::Result<()> {
        self.add_card_then(client_time_ms, soul_card_id, card_key,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_card_then(
        &self,
        client_time_ms: u64,
soul_card_id: u32,
card_key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_card for super::RemoteReducers {
    fn add_card_then(
        &self,
        client_time_ms: u64,
soul_card_id: u32,
card_key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AddCardArgs { client_time_ms, soul_card_id, card_key,  }, callback)
    }
}

