// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyActionTileArgs {
    pub now_ms: u64,
    pub completion_ms: u64,
    pub surface: u8,
    pub macro_zone: u64,
    pub q: u8,
    pub r: u8,
    pub hold_mask: u8,
    pub stock_slots: Vec::<u8>,
    pub stock_ops: Vec::<u8>,
    pub stock_deltas: Vec::<u8>,
}

impl From<ApplyActionTileArgs> for super::Reducer {
    fn from(args: ApplyActionTileArgs) -> Self {
        Self::ApplyActionTile {
            now_ms: args.now_ms,
            completion_ms: args.completion_ms,
            surface: args.surface,
            macro_zone: args.macro_zone,
            q: args.q,
            r: args.r,
            hold_mask: args.hold_mask,
            stock_slots: args.stock_slots,
            stock_ops: args.stock_ops,
            stock_deltas: args.stock_deltas,
}
}
}

impl __sdk::InModule for ApplyActionTileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_action_tile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_action_tile {
    /// Request that the remote module invoke the reducer `apply_action_tile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_action_tile:apply_action_tile_then`] to run a callback after the reducer completes.
    fn apply_action_tile(&self, now_ms: u64,
completion_ms: u64,
surface: u8,
macro_zone: u64,
q: u8,
r: u8,
hold_mask: u8,
stock_slots: Vec::<u8>,
stock_ops: Vec::<u8>,
stock_deltas: Vec::<u8>,
) -> __sdk::Result<()> {
        self.apply_action_tile_then(now_ms, completion_ms, surface, macro_zone, q, r, hold_mask, stock_slots, stock_ops, stock_deltas,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_action_tile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_action_tile_then(
        &self,
        now_ms: u64,
completion_ms: u64,
surface: u8,
macro_zone: u64,
q: u8,
r: u8,
hold_mask: u8,
stock_slots: Vec::<u8>,
stock_ops: Vec::<u8>,
stock_deltas: Vec::<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_action_tile for super::RemoteReducers {
    fn apply_action_tile_then(
        &self,
        now_ms: u64,
completion_ms: u64,
surface: u8,
macro_zone: u64,
q: u8,
r: u8,
hold_mask: u8,
stock_slots: Vec::<u8>,
stock_ops: Vec::<u8>,
stock_deltas: Vec::<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ApplyActionTileArgs { now_ms, completion_ms, surface, macro_zone, q, r, hold_mask, stock_slots, stock_ops, stock_deltas,  }, callback)
    }
}

