// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ApplyActionArgs {
    pub now_ms: u64,
    pub completion_ms: u64,
    pub bound_ids: Vec::<u32>,
    pub bound_masks: Vec::<u8>,
    pub destroy_ids: Vec::<u32>,
    pub create_defs: Vec::<u16>,
    pub create_surfaces: Vec::<u8>,
    pub create_macro_zones: Vec::<u64>,
    pub create_owners: Vec::<u32>,
    pub create_distances: Vec::<u16>,
    pub create_stocks: Vec::<u32>,
    pub create_tags: Vec::<u8>,
    pub create_cells: Vec::<i64>,
    pub stat_souls: Vec::<u32>,
    pub stat_fields: Vec::<u8>,
    pub stat_bytes: Vec::<u8>,
    pub stat_deltas: Vec::<i8>,
    pub stock_card_ids: Vec::<u32>,
    pub stock_values: Vec::<u32>,
    pub reroot_ids: Vec::<u32>,
    pub reroot_macro_zones: Vec::<u64>,
    pub reroot_micro_locations: Vec::<u32>,
    pub reroot_stack_states: Vec::<u8>,
    pub move_ids: Vec::<u32>,
    pub move_surfaces: Vec::<u8>,
    pub move_macro_zones: Vec::<u64>,
    pub move_owners: Vec::<u32>,
    pub move_distances: Vec::<u16>,
}

impl From<ApplyActionArgs> for super::Reducer {
    fn from(args: ApplyActionArgs) -> Self {
        Self::ApplyAction {
            now_ms: args.now_ms,
            completion_ms: args.completion_ms,
            bound_ids: args.bound_ids,
            bound_masks: args.bound_masks,
            destroy_ids: args.destroy_ids,
            create_defs: args.create_defs,
            create_surfaces: args.create_surfaces,
            create_macro_zones: args.create_macro_zones,
            create_owners: args.create_owners,
            create_distances: args.create_distances,
            create_stocks: args.create_stocks,
            create_tags: args.create_tags,
            create_cells: args.create_cells,
            stat_souls: args.stat_souls,
            stat_fields: args.stat_fields,
            stat_bytes: args.stat_bytes,
            stat_deltas: args.stat_deltas,
            stock_card_ids: args.stock_card_ids,
            stock_values: args.stock_values,
            reroot_ids: args.reroot_ids,
            reroot_macro_zones: args.reroot_macro_zones,
            reroot_micro_locations: args.reroot_micro_locations,
            reroot_stack_states: args.reroot_stack_states,
            move_ids: args.move_ids,
            move_surfaces: args.move_surfaces,
            move_macro_zones: args.move_macro_zones,
            move_owners: args.move_owners,
            move_distances: args.move_distances,
}
}
}

impl __sdk::InModule for ApplyActionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `apply_action`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait apply_action {
    /// Request that the remote module invoke the reducer `apply_action` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`apply_action:apply_action_then`] to run a callback after the reducer completes.
    fn apply_action(&self, now_ms: u64,
completion_ms: u64,
bound_ids: Vec::<u32>,
bound_masks: Vec::<u8>,
destroy_ids: Vec::<u32>,
create_defs: Vec::<u16>,
create_surfaces: Vec::<u8>,
create_macro_zones: Vec::<u64>,
create_owners: Vec::<u32>,
create_distances: Vec::<u16>,
create_stocks: Vec::<u32>,
create_tags: Vec::<u8>,
create_cells: Vec::<i64>,
stat_souls: Vec::<u32>,
stat_fields: Vec::<u8>,
stat_bytes: Vec::<u8>,
stat_deltas: Vec::<i8>,
stock_card_ids: Vec::<u32>,
stock_values: Vec::<u32>,
reroot_ids: Vec::<u32>,
reroot_macro_zones: Vec::<u64>,
reroot_micro_locations: Vec::<u32>,
reroot_stack_states: Vec::<u8>,
move_ids: Vec::<u32>,
move_surfaces: Vec::<u8>,
move_macro_zones: Vec::<u64>,
move_owners: Vec::<u32>,
move_distances: Vec::<u16>,
) -> __sdk::Result<()> {
        self.apply_action_then(now_ms, completion_ms, bound_ids, bound_masks, destroy_ids, create_defs, create_surfaces, create_macro_zones, create_owners, create_distances, create_stocks, create_tags, create_cells, stat_souls, stat_fields, stat_bytes, stat_deltas, stock_card_ids, stock_values, reroot_ids, reroot_macro_zones, reroot_micro_locations, reroot_stack_states, move_ids, move_surfaces, move_macro_zones, move_owners, move_distances,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `apply_action` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn apply_action_then(
        &self,
        now_ms: u64,
completion_ms: u64,
bound_ids: Vec::<u32>,
bound_masks: Vec::<u8>,
destroy_ids: Vec::<u32>,
create_defs: Vec::<u16>,
create_surfaces: Vec::<u8>,
create_macro_zones: Vec::<u64>,
create_owners: Vec::<u32>,
create_distances: Vec::<u16>,
create_stocks: Vec::<u32>,
create_tags: Vec::<u8>,
create_cells: Vec::<i64>,
stat_souls: Vec::<u32>,
stat_fields: Vec::<u8>,
stat_bytes: Vec::<u8>,
stat_deltas: Vec::<i8>,
stock_card_ids: Vec::<u32>,
stock_values: Vec::<u32>,
reroot_ids: Vec::<u32>,
reroot_macro_zones: Vec::<u64>,
reroot_micro_locations: Vec::<u32>,
reroot_stack_states: Vec::<u8>,
move_ids: Vec::<u32>,
move_surfaces: Vec::<u8>,
move_macro_zones: Vec::<u64>,
move_owners: Vec::<u32>,
move_distances: Vec::<u16>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl apply_action for super::RemoteReducers {
    fn apply_action_then(
        &self,
        now_ms: u64,
completion_ms: u64,
bound_ids: Vec::<u32>,
bound_masks: Vec::<u8>,
destroy_ids: Vec::<u32>,
create_defs: Vec::<u16>,
create_surfaces: Vec::<u8>,
create_macro_zones: Vec::<u64>,
create_owners: Vec::<u32>,
create_distances: Vec::<u16>,
create_stocks: Vec::<u32>,
create_tags: Vec::<u8>,
create_cells: Vec::<i64>,
stat_souls: Vec::<u32>,
stat_fields: Vec::<u8>,
stat_bytes: Vec::<u8>,
stat_deltas: Vec::<i8>,
stock_card_ids: Vec::<u32>,
stock_values: Vec::<u32>,
reroot_ids: Vec::<u32>,
reroot_macro_zones: Vec::<u64>,
reroot_micro_locations: Vec::<u32>,
reroot_stack_states: Vec::<u8>,
move_ids: Vec::<u32>,
move_surfaces: Vec::<u8>,
move_macro_zones: Vec::<u64>,
move_owners: Vec::<u32>,
move_distances: Vec::<u16>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ApplyActionArgs { now_ms, completion_ms, bound_ids, bound_masks, destroy_ids, create_defs, create_surfaces, create_macro_zones, create_owners, create_distances, create_stocks, create_tags, create_cells, stat_souls, stat_fields, stat_bytes, stat_deltas, stock_card_ids, stock_values, reroot_ids, reroot_macro_zones, reroot_micro_locations, reroot_stack_states, move_ids, move_surfaces, move_macro_zones, move_owners, move_distances,  }, callback)
    }
}

