// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::card_type::Card;

/// Table handle for the table `cards`.
///
/// Obtain a handle from the [`CardsTableAccess::cards`] method on [`super::RemoteTables`],
/// like `ctx.db.cards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cards().on_insert(...)`.
pub struct CardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Card>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CardsTableHandle`], which mediates access to the table `cards`.
    fn cards(&self) -> CardsTableHandle<'_>;
}

impl CardsTableAccess for super::RemoteTables {
    fn cards(&self) -> CardsTableHandle<'_> {
        CardsTableHandle {
            imp: self.imp.get_table::<Card>("cards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CardsInsertCallbackId(__sdk::CallbackId);
pub struct CardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CardsTableHandle<'ctx> {
    type Row = Card;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Card> + '_ { self.imp.iter() }

    type InsertCallbackId = CardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CardsInsertCallbackId {
        CardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CardsDeleteCallbackId {
        CardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CardsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CardsTableHandle<'ctx> {
    type UpdateCallbackId = CardsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CardsUpdateCallbackId {
        CardsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CardsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `cards`,
        /// which allows point queries on the field of the same name
        /// via the [`CardsValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.cards().valid_at().find(...)`.
        pub struct CardsValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Card, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CardsTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `cards`.
            pub fn valid_at(&self) -> CardsValidAtUnique<'ctx> {
                CardsValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CardsValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Card> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Card>("cards");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Card>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Card>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Card`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait cardsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Card`.
            fn cards(&self) -> __sdk::__query_builder::Table<Card>;
        }

        impl cardsQueryTableAccess for __sdk::QueryTableAccessor {
            fn cards(&self) -> __sdk::__query_builder::Table<Card> {
                __sdk::__query_builder::Table::new("cards")
            }
        }

