// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Card {
    pub valid_at: u64,
    pub card_id: u32,
    pub macro_zone: u64,
    pub micro_location: u32,
    pub owner_id: u32,
    pub packed_definition: u16,
    pub flags: u32,
    pub flags_bk: u8,
    pub stock: u8,
}


impl __sdk::InModule for Card {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Card`.
///
/// Provides typed access to columns for query building.
pub struct CardCols {
    pub valid_at: __sdk::__query_builder::Col<Card, u64>,
    pub card_id: __sdk::__query_builder::Col<Card, u32>,
    pub macro_zone: __sdk::__query_builder::Col<Card, u64>,
    pub micro_location: __sdk::__query_builder::Col<Card, u32>,
    pub owner_id: __sdk::__query_builder::Col<Card, u32>,
    pub packed_definition: __sdk::__query_builder::Col<Card, u16>,
    pub flags: __sdk::__query_builder::Col<Card, u32>,
    pub flags_bk: __sdk::__query_builder::Col<Card, u8>,
    pub stock: __sdk::__query_builder::Col<Card, u8>,
}

impl __sdk::__query_builder::HasCols for Card {
    type Cols = CardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CardCols {
            valid_at: __sdk::__query_builder::Col::new(table_name, "valid_at"),
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            macro_zone: __sdk::__query_builder::Col::new(table_name, "macro_zone"),
            micro_location: __sdk::__query_builder::Col::new(table_name, "micro_location"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            packed_definition: __sdk::__query_builder::Col::new(table_name, "packed_definition"),
            flags: __sdk::__query_builder::Col::new(table_name, "flags"),
            flags_bk: __sdk::__query_builder::Col::new(table_name, "flags_bk"),
            stock: __sdk::__query_builder::Col::new(table_name, "stock"),

        }
    }
}

/// Indexed column accessor struct for the table `Card`.
///
/// Provides typed access to indexed columns for query building.
pub struct CardIxCols {
    pub card_id: __sdk::__query_builder::IxCol<Card, u32>,
    pub macro_zone: __sdk::__query_builder::IxCol<Card, u64>,
    pub micro_location: __sdk::__query_builder::IxCol<Card, u32>,
    pub owner_id: __sdk::__query_builder::IxCol<Card, u32>,
    pub valid_at: __sdk::__query_builder::IxCol<Card, u64>,
}

impl __sdk::__query_builder::HasIxCols for Card {
    type IxCols = CardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CardIxCols {
            card_id: __sdk::__query_builder::IxCol::new(table_name, "card_id"),
            macro_zone: __sdk::__query_builder::IxCol::new(table_name, "macro_zone"),
            micro_location: __sdk::__query_builder::IxCol::new(table_name, "micro_location"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            valid_at: __sdk::__query_builder::IxCol::new(table_name, "valid_at"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Card {}

