// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::card_shard_type::CardShard;

/// Table handle for the table `card_shards`.
///
/// Obtain a handle from the [`CardShardsTableAccess::card_shards`] method on [`super::RemoteTables`],
/// like `ctx.db.card_shards()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.card_shards().on_insert(...)`.
pub struct CardShardsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CardShard>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `card_shards`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CardShardsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CardShardsTableHandle`], which mediates access to the table `card_shards`.
    fn card_shards(&self) -> CardShardsTableHandle<'_>;
}

impl CardShardsTableAccess for super::RemoteTables {
    fn card_shards(&self) -> CardShardsTableHandle<'_> {
        CardShardsTableHandle {
            imp: self.imp.get_table::<CardShard>("card_shards"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CardShardsInsertCallbackId(__sdk::CallbackId);
pub struct CardShardsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CardShardsTableHandle<'ctx> {
    type Row = CardShard;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = CardShard> + '_ { self.imp.iter() }

    type InsertCallbackId = CardShardsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CardShardsInsertCallbackId {
        CardShardsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CardShardsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CardShardsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CardShardsDeleteCallbackId {
        CardShardsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CardShardsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CardShardsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CardShardsTableHandle<'ctx> {
    type UpdateCallbackId = CardShardsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CardShardsUpdateCallbackId {
        CardShardsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CardShardsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `card_shards`,
        /// which allows point queries on the field of the same name
        /// via the [`CardShardsValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.card_shards().valid_at().find(...)`.
        pub struct CardShardsValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<CardShard, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> CardShardsTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `card_shards`.
            pub fn valid_at(&self) -> CardShardsValidAtUnique<'ctx> {
                CardShardsValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> CardShardsValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<CardShard> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<CardShard>("card_shards");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CardShard>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<CardShard>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `CardShard`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait card_shardsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `CardShard`.
            fn card_shards(&self) -> __sdk::__query_builder::Table<CardShard>;
        }

        impl card_shardsQueryTableAccess for __sdk::QueryTableAccessor {
            fn card_shards(&self) -> __sdk::__query_builder::Table<CardShard> {
                __sdk::__query_builder::Table::new("card_shards")
            }
        }

