// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCardArgs {
    pub client_time_ms: u64,
    pub owner_id: u32,
    pub surface: u8,
    pub packed_definition: u16,
}

impl From<CreateCardArgs> for super::Reducer {
    fn from(args: CreateCardArgs) -> Self {
        Self::CreateCard {
            client_time_ms: args.client_time_ms,
            owner_id: args.owner_id,
            surface: args.surface,
            packed_definition: args.packed_definition,
}
}
}

impl __sdk::InModule for CreateCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_card {
    /// Request that the remote module invoke the reducer `create_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_card:create_card_then`] to run a callback after the reducer completes.
    fn create_card(&self, client_time_ms: u64,
owner_id: u32,
surface: u8,
packed_definition: u16,
) -> __sdk::Result<()> {
        self.create_card_then(client_time_ms, owner_id, surface, packed_definition,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_card_then(
        &self,
        client_time_ms: u64,
owner_id: u32,
surface: u8,
packed_definition: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_card for super::RemoteReducers {
    fn create_card_then(
        &self,
        client_time_ms: u64,
owner_id: u32,
surface: u8,
packed_definition: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CreateCardArgs { client_time_ms, owner_id, surface, packed_definition,  }, callback)
    }
}

