// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnsureRegionArgs {
    pub client_time_ms: u64,
    pub macro_zone: u64,
}

impl From<EnsureRegionArgs> for super::Reducer {
    fn from(args: EnsureRegionArgs) -> Self {
        Self::EnsureRegion {
            client_time_ms: args.client_time_ms,
            macro_zone: args.macro_zone,
}
}
}

impl __sdk::InModule for EnsureRegionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ensure_region`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ensure_region {
    /// Request that the remote module invoke the reducer `ensure_region` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ensure_region:ensure_region_then`] to run a callback after the reducer completes.
    fn ensure_region(&self, client_time_ms: u64,
macro_zone: u64,
) -> __sdk::Result<()> {
        self.ensure_region_then(client_time_ms, macro_zone,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ensure_region` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ensure_region_then(
        &self,
        client_time_ms: u64,
macro_zone: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ensure_region for super::RemoteReducers {
    fn ensure_region_then(
        &self,
        client_time_ms: u64,
macro_zone: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(EnsureRegionArgs { client_time_ms, macro_zone,  }, callback)
    }
}

