// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LifecyclePending {
    pub card_id: u32,
    pub expires_at_ms: u64,
    pub player_id: u32,
}


impl __sdk::InModule for LifecyclePending {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `LifecyclePending`.
///
/// Provides typed access to columns for query building.
pub struct LifecyclePendingCols {
    pub card_id: __sdk::__query_builder::Col<LifecyclePending, u32>,
    pub expires_at_ms: __sdk::__query_builder::Col<LifecyclePending, u64>,
    pub player_id: __sdk::__query_builder::Col<LifecyclePending, u32>,
}

impl __sdk::__query_builder::HasCols for LifecyclePending {
    type Cols = LifecyclePendingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LifecyclePendingCols {
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            expires_at_ms: __sdk::__query_builder::Col::new(table_name, "expires_at_ms"),
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),

        }
    }
}

/// Indexed column accessor struct for the table `LifecyclePending`.
///
/// Provides typed access to indexed columns for query building.
pub struct LifecyclePendingIxCols {
    pub card_id: __sdk::__query_builder::IxCol<LifecyclePending, u32>,
    pub player_id: __sdk::__query_builder::IxCol<LifecyclePending, u32>,
}

impl __sdk::__query_builder::HasIxCols for LifecyclePending {
    type IxCols = LifecyclePendingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LifecyclePendingIxCols {
            card_id: __sdk::__query_builder::IxCol::new(table_name, "card_id"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LifecyclePending {}

