// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LogOpArg {
    pub card_id: u32,
    pub aspect_id: u8,
    pub op: u8,
    pub modifier: i64,
    pub time_ms: u64,
}


impl __sdk::InModule for LogOpArg {
    type Module = super::RemoteModule;
}

