// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

pub mod card_type;
pub mod card_id_counter_type;
pub mod gc_schedule_type;
pub mod lifecycle_pending_type;
pub mod pending_action_type;
pub mod placement_type;
pub mod player_type;
pub mod player_id_counter_type;
pub mod player_profile_type;
pub mod player_session_type;
pub mod region_type;
pub mod sequence_counter_type;
pub mod soul_type;
pub mod soul_private_type;
pub mod tile_point_type;
pub mod zone_type;
pub mod add_card_reducer;
pub mod bootstrap_reducer;
pub mod claim_or_login_reducer;
pub mod deploy_mini_zone_reducer;
pub mod generate_forest_terrain_reducer;
pub mod move_soul_reducer;
pub mod pickup_mini_zone_reducer;
pub mod place_card_reducer;
pub mod propose_action_reducer;
pub mod request_blueprint_reducer;
pub mod request_zone_reducer;
pub mod set_last_login_reducer;
pub mod cards_table;
pub mod player_profiles_table;
pub mod players_table;
pub mod regions_table;
pub mod soul_privates_table;
pub mod souls_table;
pub mod zones_table;

pub use card_type::Card;
pub use card_id_counter_type::CardIdCounter;
pub use gc_schedule_type::GcSchedule;
pub use lifecycle_pending_type::LifecyclePending;
pub use pending_action_type::PendingAction;
pub use placement_type::Placement;
pub use player_type::Player;
pub use player_id_counter_type::PlayerIdCounter;
pub use player_profile_type::PlayerProfile;
pub use player_session_type::PlayerSession;
pub use region_type::Region;
pub use sequence_counter_type::SequenceCounter;
pub use soul_type::Soul;
pub use soul_private_type::SoulPrivate;
pub use tile_point_type::TilePoint;
pub use zone_type::Zone;
pub use cards_table::*;
pub use player_profiles_table::*;
pub use players_table::*;
pub use regions_table::*;
pub use soul_privates_table::*;
pub use souls_table::*;
pub use zones_table::*;
pub use add_card_reducer::add_card;
pub use bootstrap_reducer::bootstrap;
pub use claim_or_login_reducer::claim_or_login;
pub use deploy_mini_zone_reducer::deploy_mini_zone;
pub use generate_forest_terrain_reducer::generate_forest_terrain;
pub use move_soul_reducer::move_soul;
pub use pickup_mini_zone_reducer::pickup_mini_zone;
pub use place_card_reducer::place_card;
pub use propose_action_reducer::propose_action;
pub use request_blueprint_reducer::request_blueprint;
pub use request_zone_reducer::request_zone;
pub use set_last_login_reducer::set_last_login;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
        AddCard {
        client_time_ms: u64,
        soul_card_id: u32,
        card_key: String,
}    ,
    Bootstrap ,
    ClaimOrLogin {
        client_time_ms: u64,
        name: String,
}    ,
    DeployMiniZone {
        client_time_ms: u64,
        anchor_card_id: u32,
        target_macro_zone: u64,
        target_local_q: u8,
        target_local_r: u8,
}    ,
    GenerateForestTerrain {
        seed: u64,
        radius: i16,
}    ,
    MoveSoul {
        client_time_ms: u64,
        soul_id: u32,
        path: Vec::<TilePoint>,
}    ,
    PickupMiniZone {
        client_time_ms: u64,
        anchor_card_id: u32,
}    ,
    PlaceCard {
        client_time_ms: u64,
        card_id: u32,
        placement: Placement,
}    ,
    ProposeAction {
        client_time_ms: u64,
        recipe_id: u16,
        surface: u8,
        macro_zone: u64,
        micro_location: u32,
        root: u32,
        bindings: Vec::<Vec::<u32>>,
}    ,
    RequestBlueprint {
        client_time_ms: u64,
        soul_card_id: u32,
        blueprint_id: u16,
        surface: u8,
        macro_zone: u64,
        micro_location: u32,
}    ,
    RequestZone {
        client_time_ms: u64,
        macro_zone: u64,
}    ,
    SetLastLogin {
        client_time_ms: u64,
}    ,
}


impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
                        Reducer::AddCard { .. } => "add_card",
            Reducer::Bootstrap => "bootstrap",
            Reducer::ClaimOrLogin { .. } => "claim_or_login",
            Reducer::DeployMiniZone { .. } => "deploy_mini_zone",
            Reducer::GenerateForestTerrain { .. } => "generate_forest_terrain",
            Reducer::MoveSoul { .. } => "move_soul",
            Reducer::PickupMiniZone { .. } => "pickup_mini_zone",
            Reducer::PlaceCard { .. } => "place_card",
            Reducer::ProposeAction { .. } => "propose_action",
            Reducer::RequestBlueprint { .. } => "request_blueprint",
            Reducer::RequestZone { .. } => "request_zone",
            Reducer::SetLastLogin { .. } => "set_last_login",
            _ => unreachable!(),
}
}
    #[allow(clippy::clone_on_copy)]
fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AddCard{
                client_time_ms,
                soul_card_id,
                card_key,
}             => __sats::bsatn::to_vec(&add_card_reducer::AddCardArgs {
                client_time_ms: client_time_ms.clone(),
                soul_card_id: soul_card_id.clone(),
                card_key: card_key.clone(),
}),
            Reducer::Bootstrap => __sats::bsatn::to_vec(&bootstrap_reducer::BootstrapArgs {
                }),
Reducer::ClaimOrLogin{
                client_time_ms,
                name,
}             => __sats::bsatn::to_vec(&claim_or_login_reducer::ClaimOrLoginArgs {
                client_time_ms: client_time_ms.clone(),
                name: name.clone(),
}),
            Reducer::DeployMiniZone{
                client_time_ms,
                anchor_card_id,
                target_macro_zone,
                target_local_q,
                target_local_r,
}             => __sats::bsatn::to_vec(&deploy_mini_zone_reducer::DeployMiniZoneArgs {
                client_time_ms: client_time_ms.clone(),
                anchor_card_id: anchor_card_id.clone(),
                target_macro_zone: target_macro_zone.clone(),
                target_local_q: target_local_q.clone(),
                target_local_r: target_local_r.clone(),
}),
            Reducer::GenerateForestTerrain{
                seed,
                radius,
}             => __sats::bsatn::to_vec(&generate_forest_terrain_reducer::GenerateForestTerrainArgs {
                seed: seed.clone(),
                radius: radius.clone(),
}),
            Reducer::MoveSoul{
                client_time_ms,
                soul_id,
                path,
}             => __sats::bsatn::to_vec(&move_soul_reducer::MoveSoulArgs {
                client_time_ms: client_time_ms.clone(),
                soul_id: soul_id.clone(),
                path: path.clone(),
}),
            Reducer::PickupMiniZone{
                client_time_ms,
                anchor_card_id,
}             => __sats::bsatn::to_vec(&pickup_mini_zone_reducer::PickupMiniZoneArgs {
                client_time_ms: client_time_ms.clone(),
                anchor_card_id: anchor_card_id.clone(),
}),
            Reducer::PlaceCard{
                client_time_ms,
                card_id,
                placement,
}             => __sats::bsatn::to_vec(&place_card_reducer::PlaceCardArgs {
                client_time_ms: client_time_ms.clone(),
                card_id: card_id.clone(),
                placement: placement.clone(),
}),
            Reducer::ProposeAction{
                client_time_ms,
                recipe_id,
                surface,
                macro_zone,
                micro_location,
                root,
                bindings,
}             => __sats::bsatn::to_vec(&propose_action_reducer::ProposeActionArgs {
                client_time_ms: client_time_ms.clone(),
                recipe_id: recipe_id.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                micro_location: micro_location.clone(),
                root: root.clone(),
                bindings: bindings.clone(),
}),
            Reducer::RequestBlueprint{
                client_time_ms,
                soul_card_id,
                blueprint_id,
                surface,
                macro_zone,
                micro_location,
}             => __sats::bsatn::to_vec(&request_blueprint_reducer::RequestBlueprintArgs {
                client_time_ms: client_time_ms.clone(),
                soul_card_id: soul_card_id.clone(),
                blueprint_id: blueprint_id.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                micro_location: micro_location.clone(),
}),
            Reducer::RequestZone{
                client_time_ms,
                macro_zone,
}             => __sats::bsatn::to_vec(&request_zone_reducer::RequestZoneArgs {
                client_time_ms: client_time_ms.clone(),
                macro_zone: macro_zone.clone(),
}),
            Reducer::SetLastLogin{
                client_time_ms,
}             => __sats::bsatn::to_vec(&set_last_login_reducer::SetLastLoginArgs {
                client_time_ms: client_time_ms.clone(),
}),
            _ => unreachable!(),
}
}
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
        cards: __sdk::TableUpdate<Card>,
    player_profiles: __sdk::TableUpdate<PlayerProfile>,
    players: __sdk::TableUpdate<Player>,
    regions: __sdk::TableUpdate<Region>,
    soul_privates: __sdk::TableUpdate<SoulPrivate>,
    souls: __sdk::TableUpdate<Soul>,
    zones: __sdk::TableUpdate<Zone>,
}


impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {

        "cards" => db_update.cards.append(cards_table::parse_table_update(table_update)?),
    "player_profiles" => db_update.player_profiles.append(player_profiles_table::parse_table_update(table_update)?),
    "players" => db_update.players.append(players_table::parse_table_update(table_update)?),
    "regions" => db_update.regions.append(regions_table::parse_table_update(table_update)?),
    "soul_privates" => db_update.soul_privates.append(soul_privates_table::parse_table_update(table_update)?),
    "souls" => db_update.souls.append(souls_table::parse_table_update(table_update)?),
    "zones" => db_update.zones.append(zones_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    ).into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
                    let mut diff = AppliedDiff::default();
                
                diff.cards = cache.apply_diff_to_table::<Card>("cards", &self.cards).with_updates_by_pk(|row| &row.valid_at);
        diff.player_profiles = cache.apply_diff_to_table::<PlayerProfile>("player_profiles", &self.player_profiles).with_updates_by_pk(|row| &row.player_id);
        diff.players = cache.apply_diff_to_table::<Player>("players", &self.players).with_updates_by_pk(|row| &row.valid_at);
        diff.regions = cache.apply_diff_to_table::<Region>("regions", &self.regions).with_updates_by_pk(|row| &row.valid_at);
        diff.soul_privates = cache.apply_diff_to_table::<SoulPrivate>("soul_privates", &self.soul_privates).with_updates_by_pk(|row| &row.card_id);
        diff.souls = cache.apply_diff_to_table::<Soul>("souls", &self.souls).with_updates_by_pk(|row| &row.valid_at);
        diff.zones = cache.apply_diff_to_table::<Zone>("zones", &self.zones).with_updates_by_pk(|row| &row.valid_at);

                    diff
                }
fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "cards" => db_update.cards.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_profiles" => db_update.player_profiles.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "players" => db_update.players.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "regions" => db_update.regions.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "soul_privates" => db_update.soul_privates.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "souls" => db_update.souls.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "zones" => db_update.zones.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "cards" => db_update.cards.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_profiles" => db_update.player_profiles.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "players" => db_update.players.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "regions" => db_update.regions.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "soul_privates" => db_update.soul_privates.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "souls" => db_update.souls.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "zones" => db_update.zones.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
        cards: __sdk::TableAppliedDiff<'r, Card>,
    player_profiles: __sdk::TableAppliedDiff<'r, PlayerProfile>,
    players: __sdk::TableAppliedDiff<'r, Player>,
    regions: __sdk::TableAppliedDiff<'r, Region>,
    soul_privates: __sdk::TableAppliedDiff<'r, SoulPrivate>,
    souls: __sdk::TableAppliedDiff<'r, Soul>,
    zones: __sdk::TableAppliedDiff<'r, Zone>,
    __unused: std::marker::PhantomData<&'r ()>,
}


impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
                callbacks.invoke_table_row_callbacks::<Card>("cards", &self.cards, event);
        callbacks.invoke_table_row_callbacks::<PlayerProfile>("player_profiles", &self.player_profiles, event);
        callbacks.invoke_table_row_callbacks::<Player>("players", &self.players, event);
        callbacks.invoke_table_row_callbacks::<Region>("regions", &self.regions, event);
        callbacks.invoke_table_row_callbacks::<SoulPrivate>("soul_privates", &self.soul_privates, event);
        callbacks.invoke_table_row_callbacks::<Soul>("souls", &self.souls, event);
        callbacks.invoke_table_row_callbacks::<Zone>("zones", &self.zones, event);
}
}


#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch =  "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }

}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
> {}
impl<Ctx: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>> RemoteDbContext for Ctx {}


/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
                cards_table::register_table(client_cache);
        player_profiles_table::register_table(client_cache);
        players_table::register_table(client_cache);
        regions_table::register_table(client_cache);
        soul_privates_table::register_table(client_cache);
        souls_table::register_table(client_cache);
        zones_table::register_table(client_cache);
}
const ALL_TABLE_NAMES: &'static [&'static str] = &[
                "cards",
        "player_profiles",
        "players",
        "regions",
        "soul_privates",
        "souls",
        "zones",
];
}
