// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

pub mod card_type;
pub mod card_id_counter_type;
pub mod card_shard_type;
pub mod gc_schedule_type;
pub mod pending_action_type;
pub mod placement_type;
pub mod region_type;
pub mod sequence_counter_type;
pub mod shard_identity_type;
pub mod soul_type;
pub mod tile_point_type;
pub mod zone_type;
pub mod acquire_card_shard_reducer;
pub mod apply_action_reducer;
pub mod apply_action_tile_reducer;
pub mod claim_pending_reducer;
pub mod create_card_reducer;
pub mod ensure_region_reducer;
pub mod move_card_reducer;
pub mod move_cards_reducer;
pub mod place_card_reducer;
pub mod release_card_shard_reducer;
pub mod release_pending_reducer;
pub mod request_zone_reducer;
pub mod set_shard_identity_reducer;
pub mod card_shards_table;
pub mod cards_table;
pub mod regions_table;
pub mod souls_table;
pub mod zones_table;

pub use card_type::Card;
pub use card_id_counter_type::CardIdCounter;
pub use card_shard_type::CardShard;
pub use gc_schedule_type::GcSchedule;
pub use pending_action_type::PendingAction;
pub use placement_type::Placement;
pub use region_type::Region;
pub use sequence_counter_type::SequenceCounter;
pub use shard_identity_type::ShardIdentity;
pub use soul_type::Soul;
pub use tile_point_type::TilePoint;
pub use zone_type::Zone;
pub use card_shards_table::*;
pub use cards_table::*;
pub use regions_table::*;
pub use souls_table::*;
pub use zones_table::*;
pub use acquire_card_shard_reducer::acquire_card_shard;
pub use apply_action_reducer::apply_action;
pub use apply_action_tile_reducer::apply_action_tile;
pub use claim_pending_reducer::claim_pending;
pub use create_card_reducer::create_card;
pub use ensure_region_reducer::ensure_region;
pub use move_card_reducer::move_card;
pub use move_cards_reducer::move_cards;
pub use place_card_reducer::place_card;
pub use release_card_shard_reducer::release_card_shard;
pub use release_pending_reducer::release_pending;
pub use request_zone_reducer::request_zone;
pub use set_shard_identity_reducer::set_shard_identity;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
        AcquireCardShard {
        time_ms: u64,
        data_shard: u16,
}    ,
    ApplyAction {
        now_ms: u64,
        completion_ms: u64,
        bound_ids: Vec::<u32>,
        bound_masks: Vec::<u8>,
        destroy_ids: Vec::<u32>,
        create_defs: Vec::<u16>,
        create_surfaces: Vec::<u8>,
        create_macro_zones: Vec::<u64>,
        create_owners: Vec::<u32>,
        create_distances: Vec::<u16>,
        create_stocks: Vec::<u64>,
        create_tags: Vec::<u8>,
        create_cells: Vec::<i64>,
        stat_souls: Vec::<u32>,
        stat_fields: Vec::<u8>,
        stat_bytes: Vec::<u8>,
        stat_deltas: Vec::<i8>,
        stock_card_ids: Vec::<u32>,
        stock_values: Vec::<u64>,
        reroot_ids: Vec::<u32>,
        reroot_macro_zones: Vec::<u64>,
        reroot_micro_locations: Vec::<u32>,
        reroot_stack_states: Vec::<u8>,
        move_ids: Vec::<u32>,
        move_surfaces: Vec::<u8>,
        move_macro_zones: Vec::<u64>,
        move_owners: Vec::<u32>,
        move_distances: Vec::<u16>,
}    ,
    ApplyActionTile {
        now_ms: u64,
        completion_ms: u64,
        surface: u8,
        macro_zone: u64,
        q: u8,
        r: u8,
        hold_mask: u8,
        stock_slots: Vec::<u8>,
        stock_ops: Vec::<u8>,
        stock_deltas: Vec::<u8>,
}    ,
    ClaimPending {
        recipe_id: u16,
        root: u32,
        bindings: Vec::<Vec::<u32>>,
        completion_ms: u64,
}    ,
    CreateCard {
        client_time_ms: u64,
        owner_id: u32,
        surface: u8,
        packed_definition: u16,
        stock: u64,
        macro_zone: u64,
        q: u8,
        r: u8,
        distance: u16,
}    ,
    EnsureRegion {
        client_time_ms: u64,
        macro_zone: u64,
        distance: u16,
}    ,
    MoveCard {
        client_time_ms: u64,
        caller_player_id: u32,
        soul_id: u32,
        soul_def: u16,
        from_q: i32,
        from_r: i32,
        dest: TilePoint,
        depart_ms: u64,
        arrival_ms: u64,
}    ,
    MoveCards {
        client_time_ms: u64,
        caller_player_id: u32,
        card_ids: Vec::<u32>,
        macro_zones: Vec::<u64>,
        micro_locations: Vec::<u32>,
        stack_states: Vec::<u8>,
}    ,
    PlaceCard {
        client_time_ms: u64,
        caller_player_id: u32,
        card_id: u32,
        placement: Placement,
}    ,
    ReleaseCardShard {
        time_ms: u64,
        data_shard: u16,
}    ,
    ReleasePending {
        recipe_id: u16,
        root: u32,
        bindings: Vec::<Vec::<u32>>,
}    ,
    RequestZone {
        client_time_ms: u64,
        macro_zone: u64,
        tiles: Vec::<u64>,
}    ,
    SetShardIdentity {
        card_db: u8,
        shard: u16,
}    ,
}


impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
                        Reducer::AcquireCardShard { .. } => "acquire_card_shard",
            Reducer::ApplyAction { .. } => "apply_action",
            Reducer::ApplyActionTile { .. } => "apply_action_tile",
            Reducer::ClaimPending { .. } => "claim_pending",
            Reducer::CreateCard { .. } => "create_card",
            Reducer::EnsureRegion { .. } => "ensure_region",
            Reducer::MoveCard { .. } => "move_card",
            Reducer::MoveCards { .. } => "move_cards",
            Reducer::PlaceCard { .. } => "place_card",
            Reducer::ReleaseCardShard { .. } => "release_card_shard",
            Reducer::ReleasePending { .. } => "release_pending",
            Reducer::RequestZone { .. } => "request_zone",
            Reducer::SetShardIdentity { .. } => "set_shard_identity",
            _ => unreachable!(),
}
}
    #[allow(clippy::clone_on_copy)]
fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AcquireCardShard{
                time_ms,
                data_shard,
}             => __sats::bsatn::to_vec(&acquire_card_shard_reducer::AcquireCardShardArgs {
                time_ms: time_ms.clone(),
                data_shard: data_shard.clone(),
}),
            Reducer::ApplyAction{
                now_ms,
                completion_ms,
                bound_ids,
                bound_masks,
                destroy_ids,
                create_defs,
                create_surfaces,
                create_macro_zones,
                create_owners,
                create_distances,
                create_stocks,
                create_tags,
                create_cells,
                stat_souls,
                stat_fields,
                stat_bytes,
                stat_deltas,
                stock_card_ids,
                stock_values,
                reroot_ids,
                reroot_macro_zones,
                reroot_micro_locations,
                reroot_stack_states,
                move_ids,
                move_surfaces,
                move_macro_zones,
                move_owners,
                move_distances,
}             => __sats::bsatn::to_vec(&apply_action_reducer::ApplyActionArgs {
                now_ms: now_ms.clone(),
                completion_ms: completion_ms.clone(),
                bound_ids: bound_ids.clone(),
                bound_masks: bound_masks.clone(),
                destroy_ids: destroy_ids.clone(),
                create_defs: create_defs.clone(),
                create_surfaces: create_surfaces.clone(),
                create_macro_zones: create_macro_zones.clone(),
                create_owners: create_owners.clone(),
                create_distances: create_distances.clone(),
                create_stocks: create_stocks.clone(),
                create_tags: create_tags.clone(),
                create_cells: create_cells.clone(),
                stat_souls: stat_souls.clone(),
                stat_fields: stat_fields.clone(),
                stat_bytes: stat_bytes.clone(),
                stat_deltas: stat_deltas.clone(),
                stock_card_ids: stock_card_ids.clone(),
                stock_values: stock_values.clone(),
                reroot_ids: reroot_ids.clone(),
                reroot_macro_zones: reroot_macro_zones.clone(),
                reroot_micro_locations: reroot_micro_locations.clone(),
                reroot_stack_states: reroot_stack_states.clone(),
                move_ids: move_ids.clone(),
                move_surfaces: move_surfaces.clone(),
                move_macro_zones: move_macro_zones.clone(),
                move_owners: move_owners.clone(),
                move_distances: move_distances.clone(),
}),
            Reducer::ApplyActionTile{
                now_ms,
                completion_ms,
                surface,
                macro_zone,
                q,
                r,
                hold_mask,
                stock_slots,
                stock_ops,
                stock_deltas,
}             => __sats::bsatn::to_vec(&apply_action_tile_reducer::ApplyActionTileArgs {
                now_ms: now_ms.clone(),
                completion_ms: completion_ms.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                q: q.clone(),
                r: r.clone(),
                hold_mask: hold_mask.clone(),
                stock_slots: stock_slots.clone(),
                stock_ops: stock_ops.clone(),
                stock_deltas: stock_deltas.clone(),
}),
            Reducer::ClaimPending{
                recipe_id,
                root,
                bindings,
                completion_ms,
}             => __sats::bsatn::to_vec(&claim_pending_reducer::ClaimPendingArgs {
                recipe_id: recipe_id.clone(),
                root: root.clone(),
                bindings: bindings.clone(),
                completion_ms: completion_ms.clone(),
}),
            Reducer::CreateCard{
                client_time_ms,
                owner_id,
                surface,
                packed_definition,
                stock,
                macro_zone,
                q,
                r,
                distance,
}             => __sats::bsatn::to_vec(&create_card_reducer::CreateCardArgs {
                client_time_ms: client_time_ms.clone(),
                owner_id: owner_id.clone(),
                surface: surface.clone(),
                packed_definition: packed_definition.clone(),
                stock: stock.clone(),
                macro_zone: macro_zone.clone(),
                q: q.clone(),
                r: r.clone(),
                distance: distance.clone(),
}),
            Reducer::EnsureRegion{
                client_time_ms,
                macro_zone,
                distance,
}             => __sats::bsatn::to_vec(&ensure_region_reducer::EnsureRegionArgs {
                client_time_ms: client_time_ms.clone(),
                macro_zone: macro_zone.clone(),
                distance: distance.clone(),
}),
            Reducer::MoveCard{
                client_time_ms,
                caller_player_id,
                soul_id,
                soul_def,
                from_q,
                from_r,
                dest,
                depart_ms,
                arrival_ms,
}             => __sats::bsatn::to_vec(&move_card_reducer::MoveCardArgs {
                client_time_ms: client_time_ms.clone(),
                caller_player_id: caller_player_id.clone(),
                soul_id: soul_id.clone(),
                soul_def: soul_def.clone(),
                from_q: from_q.clone(),
                from_r: from_r.clone(),
                dest: dest.clone(),
                depart_ms: depart_ms.clone(),
                arrival_ms: arrival_ms.clone(),
}),
            Reducer::MoveCards{
                client_time_ms,
                caller_player_id,
                card_ids,
                macro_zones,
                micro_locations,
                stack_states,
}             => __sats::bsatn::to_vec(&move_cards_reducer::MoveCardsArgs {
                client_time_ms: client_time_ms.clone(),
                caller_player_id: caller_player_id.clone(),
                card_ids: card_ids.clone(),
                macro_zones: macro_zones.clone(),
                micro_locations: micro_locations.clone(),
                stack_states: stack_states.clone(),
}),
            Reducer::PlaceCard{
                client_time_ms,
                caller_player_id,
                card_id,
                placement,
}             => __sats::bsatn::to_vec(&place_card_reducer::PlaceCardArgs {
                client_time_ms: client_time_ms.clone(),
                caller_player_id: caller_player_id.clone(),
                card_id: card_id.clone(),
                placement: placement.clone(),
}),
            Reducer::ReleaseCardShard{
                time_ms,
                data_shard,
}             => __sats::bsatn::to_vec(&release_card_shard_reducer::ReleaseCardShardArgs {
                time_ms: time_ms.clone(),
                data_shard: data_shard.clone(),
}),
            Reducer::ReleasePending{
                recipe_id,
                root,
                bindings,
}             => __sats::bsatn::to_vec(&release_pending_reducer::ReleasePendingArgs {
                recipe_id: recipe_id.clone(),
                root: root.clone(),
                bindings: bindings.clone(),
}),
            Reducer::RequestZone{
                client_time_ms,
                macro_zone,
                tiles,
}             => __sats::bsatn::to_vec(&request_zone_reducer::RequestZoneArgs {
                client_time_ms: client_time_ms.clone(),
                macro_zone: macro_zone.clone(),
                tiles: tiles.clone(),
}),
            Reducer::SetShardIdentity{
                card_db,
                shard,
}             => __sats::bsatn::to_vec(&set_shard_identity_reducer::SetShardIdentityArgs {
                card_db: card_db.clone(),
                shard: shard.clone(),
}),
            _ => unreachable!(),
}
}
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
        card_shards: __sdk::TableUpdate<CardShard>,
    cards: __sdk::TableUpdate<Card>,
    regions: __sdk::TableUpdate<Region>,
    souls: __sdk::TableUpdate<Soul>,
    zones: __sdk::TableUpdate<Zone>,
}


impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {

        "card_shards" => db_update.card_shards.append(card_shards_table::parse_table_update(table_update)?),
    "cards" => db_update.cards.append(cards_table::parse_table_update(table_update)?),
    "regions" => db_update.regions.append(regions_table::parse_table_update(table_update)?),
    "souls" => db_update.souls.append(souls_table::parse_table_update(table_update)?),
    "zones" => db_update.zones.append(zones_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    ).into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
                    let mut diff = AppliedDiff::default();
                
                diff.card_shards = cache.apply_diff_to_table::<CardShard>("card_shards", &self.card_shards).with_updates_by_pk(|row| &row.valid_at);
        diff.cards = cache.apply_diff_to_table::<Card>("cards", &self.cards).with_updates_by_pk(|row| &row.valid_at);
        diff.regions = cache.apply_diff_to_table::<Region>("regions", &self.regions).with_updates_by_pk(|row| &row.macro_region);
        diff.souls = cache.apply_diff_to_table::<Soul>("souls", &self.souls).with_updates_by_pk(|row| &row.valid_at);
        diff.zones = cache.apply_diff_to_table::<Zone>("zones", &self.zones).with_updates_by_pk(|row| &row.valid_at);

                    diff
                }
fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "card_shards" => db_update.card_shards.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "cards" => db_update.cards.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "regions" => db_update.regions.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "souls" => db_update.souls.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "zones" => db_update.zones.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "card_shards" => db_update.card_shards.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "cards" => db_update.cards.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "regions" => db_update.regions.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "souls" => db_update.souls.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "zones" => db_update.zones.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
        card_shards: __sdk::TableAppliedDiff<'r, CardShard>,
    cards: __sdk::TableAppliedDiff<'r, Card>,
    regions: __sdk::TableAppliedDiff<'r, Region>,
    souls: __sdk::TableAppliedDiff<'r, Soul>,
    zones: __sdk::TableAppliedDiff<'r, Zone>,
    __unused: std::marker::PhantomData<&'r ()>,
}


impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
                callbacks.invoke_table_row_callbacks::<CardShard>("card_shards", &self.card_shards, event);
        callbacks.invoke_table_row_callbacks::<Card>("cards", &self.cards, event);
        callbacks.invoke_table_row_callbacks::<Region>("regions", &self.regions, event);
        callbacks.invoke_table_row_callbacks::<Soul>("souls", &self.souls, event);
        callbacks.invoke_table_row_callbacks::<Zone>("zones", &self.zones, event);
}
}


#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch =  "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }

}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
> {}
impl<Ctx: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>> RemoteDbContext for Ctx {}


/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
                card_shards_table::register_table(client_cache);
        cards_table::register_table(client_cache);
        regions_table::register_table(client_cache);
        souls_table::register_table(client_cache);
        zones_table::register_table(client_cache);
}
const ALL_TABLE_NAMES: &'static [&'static str] = &[
                "card_shards",
        "cards",
        "regions",
        "souls",
        "zones",
];
}
