// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::tile_point_type::TilePoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveCardArgs {
    pub client_time_ms: u64,
    pub caller_player_id: u32,
    pub soul_id: u32,
    pub soul_def: u16,
    pub from_q: i32,
    pub from_r: i32,
    pub dest: TilePoint,
    pub depart_ms: u64,
    pub arrival_ms: u64,
}

impl From<MoveCardArgs> for super::Reducer {
    fn from(args: MoveCardArgs) -> Self {
        Self::MoveCard {
            client_time_ms: args.client_time_ms,
            caller_player_id: args.caller_player_id,
            soul_id: args.soul_id,
            soul_def: args.soul_def,
            from_q: args.from_q,
            from_r: args.from_r,
            dest: args.dest,
            depart_ms: args.depart_ms,
            arrival_ms: args.arrival_ms,
}
}
}

impl __sdk::InModule for MoveCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_card {
    /// Request that the remote module invoke the reducer `move_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_card:move_card_then`] to run a callback after the reducer completes.
    fn move_card(&self, client_time_ms: u64,
caller_player_id: u32,
soul_id: u32,
soul_def: u16,
from_q: i32,
from_r: i32,
dest: TilePoint,
depart_ms: u64,
arrival_ms: u64,
) -> __sdk::Result<()> {
        self.move_card_then(client_time_ms, caller_player_id, soul_id, soul_def, from_q, from_r, dest, depart_ms, arrival_ms,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_card_then(
        &self,
        client_time_ms: u64,
caller_player_id: u32,
soul_id: u32,
soul_def: u16,
from_q: i32,
from_r: i32,
dest: TilePoint,
depart_ms: u64,
arrival_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_card for super::RemoteReducers {
    fn move_card_then(
        &self,
        client_time_ms: u64,
caller_player_id: u32,
soul_id: u32,
soul_def: u16,
from_q: i32,
from_r: i32,
dest: TilePoint,
depart_ms: u64,
arrival_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MoveCardArgs { client_time_ms, caller_player_id, soul_id, soul_def, from_q, from_r, dest, depart_ms, arrival_ms,  }, callback)
    }
}

