// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OpLog {
    pub id: u64,
    pub card_id: u32,
    pub aspect_id: u8,
    pub time_ms: u64,
    pub op: u8,
    pub modifier: i64,
}


impl __sdk::InModule for OpLog {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `OpLog`.
///
/// Provides typed access to columns for query building.
pub struct OpLogCols {
    pub id: __sdk::__query_builder::Col<OpLog, u64>,
    pub card_id: __sdk::__query_builder::Col<OpLog, u32>,
    pub aspect_id: __sdk::__query_builder::Col<OpLog, u8>,
    pub time_ms: __sdk::__query_builder::Col<OpLog, u64>,
    pub op: __sdk::__query_builder::Col<OpLog, u8>,
    pub modifier: __sdk::__query_builder::Col<OpLog, i64>,
}

impl __sdk::__query_builder::HasCols for OpLog {
    type Cols = OpLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OpLogCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            aspect_id: __sdk::__query_builder::Col::new(table_name, "aspect_id"),
            time_ms: __sdk::__query_builder::Col::new(table_name, "time_ms"),
            op: __sdk::__query_builder::Col::new(table_name, "op"),
            modifier: __sdk::__query_builder::Col::new(table_name, "modifier"),

        }
    }
}

/// Indexed column accessor struct for the table `OpLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct OpLogIxCols {
    pub card_id: __sdk::__query_builder::IxCol<OpLog, u32>,
    pub id: __sdk::__query_builder::IxCol<OpLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for OpLog {
    type IxCols = OpLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OpLogIxCols {
            card_id: __sdk::__query_builder::IxCol::new(table_name, "card_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OpLog {}

