// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PickupMiniZoneArgs {
    pub client_time_ms: u64,
    pub anchor_card_id: u32,
}

impl From<PickupMiniZoneArgs> for super::Reducer {
    fn from(args: PickupMiniZoneArgs) -> Self {
        Self::PickupMiniZone {
            client_time_ms: args.client_time_ms,
            anchor_card_id: args.anchor_card_id,
}
}
}

impl __sdk::InModule for PickupMiniZoneArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pickup_mini_zone`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pickup_mini_zone {
    /// Request that the remote module invoke the reducer `pickup_mini_zone` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pickup_mini_zone:pickup_mini_zone_then`] to run a callback after the reducer completes.
    fn pickup_mini_zone(&self, client_time_ms: u64,
anchor_card_id: u32,
) -> __sdk::Result<()> {
        self.pickup_mini_zone_then(client_time_ms, anchor_card_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pickup_mini_zone` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pickup_mini_zone_then(
        &self,
        client_time_ms: u64,
anchor_card_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl pickup_mini_zone for super::RemoteReducers {
    fn pickup_mini_zone_then(
        &self,
        client_time_ms: u64,
anchor_card_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PickupMiniZoneArgs { client_time_ms, anchor_card_id,  }, callback)
    }
}

