// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

use super::placement_type::Placement;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlaceCardArgs {
    pub client_time_ms: u64,
    pub caller_player_id: u32,
    pub card_id: u32,
    pub placement: Placement,
}

impl From<PlaceCardArgs> for super::Reducer {
    fn from(args: PlaceCardArgs) -> Self {
        Self::PlaceCard {
            client_time_ms: args.client_time_ms,
            caller_player_id: args.caller_player_id,
            card_id: args.card_id,
            placement: args.placement,
}
}
}

impl __sdk::InModule for PlaceCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `place_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait place_card {
    /// Request that the remote module invoke the reducer `place_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`place_card:place_card_then`] to run a callback after the reducer completes.
    fn place_card(&self, client_time_ms: u64,
caller_player_id: u32,
card_id: u32,
placement: Placement,
) -> __sdk::Result<()> {
        self.place_card_then(client_time_ms, caller_player_id, card_id, placement,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `place_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn place_card_then(
        &self,
        client_time_ms: u64,
caller_player_id: u32,
card_id: u32,
placement: Placement,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl place_card for super::RemoteReducers {
    fn place_card_then(
        &self,
        client_time_ms: u64,
caller_player_id: u32,
card_id: u32,
placement: Placement,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(PlaceCardArgs { client_time_ms, caller_player_id, card_id, placement,  }, callback)
    }
}

