// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::region_type::Region;

/// Table handle for the table `regions`.
///
/// Obtain a handle from the [`RegionsTableAccess::regions`] method on [`super::RemoteTables`],
/// like `ctx.db.regions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.regions().on_insert(...)`.
pub struct RegionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Region>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `regions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RegionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RegionsTableHandle`], which mediates access to the table `regions`.
    fn regions(&self) -> RegionsTableHandle<'_>;
}

impl RegionsTableAccess for super::RemoteTables {
    fn regions(&self) -> RegionsTableHandle<'_> {
        RegionsTableHandle {
            imp: self.imp.get_table::<Region>("regions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RegionsInsertCallbackId(__sdk::CallbackId);
pub struct RegionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RegionsTableHandle<'ctx> {
    type Row = Region;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Region> + '_ { self.imp.iter() }

    type InsertCallbackId = RegionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionsInsertCallbackId {
        RegionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RegionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RegionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionsDeleteCallbackId {
        RegionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RegionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RegionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RegionsTableHandle<'ctx> {
    type UpdateCallbackId = RegionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RegionsUpdateCallbackId {
        RegionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RegionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `regions`,
        /// which allows point queries on the field of the same name
        /// via the [`RegionsValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.regions().valid_at().find(...)`.
        pub struct RegionsValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Region, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> RegionsTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `regions`.
            pub fn valid_at(&self) -> RegionsValidAtUnique<'ctx> {
                RegionsValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> RegionsValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Region> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Region>("regions");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Region>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Region>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Region`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait regionsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Region`.
            fn regions(&self) -> __sdk::__query_builder::Table<Region>;
        }

        impl regionsQueryTableAccess for __sdk::QueryTableAccessor {
            fn regions(&self) -> __sdk::__query_builder::Table<Region> {
                __sdk::__query_builder::Table::new("regions")
            }
        }

