// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestBlueprintArgs {
    pub client_time_ms: u64,
    pub soul_card_id: u32,
    pub blueprint_id: u16,
    pub surface: u8,
    pub macro_zone: u64,
    pub micro_location: u32,
}

impl From<RequestBlueprintArgs> for super::Reducer {
    fn from(args: RequestBlueprintArgs) -> Self {
        Self::RequestBlueprint {
            client_time_ms: args.client_time_ms,
            soul_card_id: args.soul_card_id,
            blueprint_id: args.blueprint_id,
            surface: args.surface,
            macro_zone: args.macro_zone,
            micro_location: args.micro_location,
}
}
}

impl __sdk::InModule for RequestBlueprintArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_blueprint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_blueprint {
    /// Request that the remote module invoke the reducer `request_blueprint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_blueprint:request_blueprint_then`] to run a callback after the reducer completes.
    fn request_blueprint(&self, client_time_ms: u64,
soul_card_id: u32,
blueprint_id: u16,
surface: u8,
macro_zone: u64,
micro_location: u32,
) -> __sdk::Result<()> {
        self.request_blueprint_then(client_time_ms, soul_card_id, blueprint_id, surface, macro_zone, micro_location,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_blueprint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_blueprint_then(
        &self,
        client_time_ms: u64,
soul_card_id: u32,
blueprint_id: u16,
surface: u8,
macro_zone: u64,
micro_location: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_blueprint for super::RemoteReducers {
    fn request_blueprint_then(
        &self,
        client_time_ms: u64,
soul_card_id: u32,
blueprint_id: u16,
surface: u8,
macro_zone: u64,
micro_location: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(RequestBlueprintArgs { client_time_ms, soul_card_id, blueprint_id, surface, macro_zone, micro_location,  }, callback)
    }
}

