// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetShardIdentityArgs {
    pub card_db: u8,
    pub shard: u16,
}

impl From<SetShardIdentityArgs> for super::Reducer {
    fn from(args: SetShardIdentityArgs) -> Self {
        Self::SetShardIdentity {
            card_db: args.card_db,
            shard: args.shard,
}
}
}

impl __sdk::InModule for SetShardIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_shard_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_shard_identity {
    /// Request that the remote module invoke the reducer `set_shard_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_shard_identity:set_shard_identity_then`] to run a callback after the reducer completes.
    fn set_shard_identity(&self, card_db: u8,
shard: u16,
) -> __sdk::Result<()> {
        self.set_shard_identity_then(card_db, shard,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_shard_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_shard_identity_then(
        &self,
        card_db: u8,
shard: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_shard_identity for super::RemoteReducers {
    fn set_shard_identity_then(
        &self,
        card_db: u8,
shard: u16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetShardIdentityArgs { card_db, shard,  }, callback)
    }
}

