// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ShardIdentity {
    pub id: u8,
    pub card_db: u8,
    pub shard: u16,
}


impl __sdk::InModule for ShardIdentity {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `ShardIdentity`.
///
/// Provides typed access to columns for query building.
pub struct ShardIdentityCols {
    pub id: __sdk::__query_builder::Col<ShardIdentity, u8>,
    pub card_db: __sdk::__query_builder::Col<ShardIdentity, u8>,
    pub shard: __sdk::__query_builder::Col<ShardIdentity, u16>,
}

impl __sdk::__query_builder::HasCols for ShardIdentity {
    type Cols = ShardIdentityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ShardIdentityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            card_db: __sdk::__query_builder::Col::new(table_name, "card_db"),
            shard: __sdk::__query_builder::Col::new(table_name, "shard"),

        }
    }
}

/// Indexed column accessor struct for the table `ShardIdentity`.
///
/// Provides typed access to indexed columns for query building.
pub struct ShardIdentityIxCols {
    pub id: __sdk::__query_builder::IxCol<ShardIdentity, u8>,
}

impl __sdk::__query_builder::HasIxCols for ShardIdentity {
    type IxCols = ShardIdentityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ShardIdentityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ShardIdentity {}

