// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::soul_private_type::SoulPrivate;

/// Table handle for the table `soul_privates`.
///
/// Obtain a handle from the [`SoulPrivatesTableAccess::soul_privates`] method on [`super::RemoteTables`],
/// like `ctx.db.soul_privates()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.soul_privates().on_insert(...)`.
pub struct SoulPrivatesTableHandle<'ctx> {
    imp: __sdk::TableHandle<SoulPrivate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `soul_privates`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SoulPrivatesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SoulPrivatesTableHandle`], which mediates access to the table `soul_privates`.
    fn soul_privates(&self) -> SoulPrivatesTableHandle<'_>;
}

impl SoulPrivatesTableAccess for super::RemoteTables {
    fn soul_privates(&self) -> SoulPrivatesTableHandle<'_> {
        SoulPrivatesTableHandle {
            imp: self.imp.get_table::<SoulPrivate>("soul_privates"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SoulPrivatesInsertCallbackId(__sdk::CallbackId);
pub struct SoulPrivatesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SoulPrivatesTableHandle<'ctx> {
    type Row = SoulPrivate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = SoulPrivate> + '_ { self.imp.iter() }

    type InsertCallbackId = SoulPrivatesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SoulPrivatesInsertCallbackId {
        SoulPrivatesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SoulPrivatesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SoulPrivatesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SoulPrivatesDeleteCallbackId {
        SoulPrivatesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SoulPrivatesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SoulPrivatesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SoulPrivatesTableHandle<'ctx> {
    type UpdateCallbackId = SoulPrivatesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SoulPrivatesUpdateCallbackId {
        SoulPrivatesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SoulPrivatesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `card_id` unique index on the table `soul_privates`,
        /// which allows point queries on the field of the same name
        /// via the [`SoulPrivatesCardIdUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.soul_privates().card_id().find(...)`.
        pub struct SoulPrivatesCardIdUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<SoulPrivate, u32>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> SoulPrivatesTableHandle<'ctx> {
            /// Get a handle on the `card_id` unique index on the table `soul_privates`.
            pub fn card_id(&self) -> SoulPrivatesCardIdUnique<'ctx> {
                SoulPrivatesCardIdUnique {
                    imp: self.imp.get_unique_constraint::<u32>("card_id"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> SoulPrivatesCardIdUnique<'ctx> {
            /// Find the subscribed row whose `card_id` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u32) -> Option<SoulPrivate> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<SoulPrivate>("soul_privates");
    _table.add_unique_constraint::<u32>("card_id", |row| &row.card_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SoulPrivate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<SoulPrivate>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `SoulPrivate`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait soul_privatesQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `SoulPrivate`.
            fn soul_privates(&self) -> __sdk::__query_builder::Table<SoulPrivate>;
        }

        impl soul_privatesQueryTableAccess for __sdk::QueryTableAccessor {
            fn soul_privates(&self) -> __sdk::__query_builder::Table<SoulPrivate> {
                __sdk::__query_builder::Table::new("soul_privates")
            }
        }

