// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SoulPrivate {
    pub card_id: u32,
    pub data_shard: u16,
    pub blueprints_0: u64,
    pub active_blueprints: u8,
}


impl __sdk::InModule for SoulPrivate {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `SoulPrivate`.
///
/// Provides typed access to columns for query building.
pub struct SoulPrivateCols {
    pub card_id: __sdk::__query_builder::Col<SoulPrivate, u32>,
    pub data_shard: __sdk::__query_builder::Col<SoulPrivate, u16>,
    pub blueprints_0: __sdk::__query_builder::Col<SoulPrivate, u64>,
    pub active_blueprints: __sdk::__query_builder::Col<SoulPrivate, u8>,
}

impl __sdk::__query_builder::HasCols for SoulPrivate {
    type Cols = SoulPrivateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SoulPrivateCols {
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            data_shard: __sdk::__query_builder::Col::new(table_name, "data_shard"),
            blueprints_0: __sdk::__query_builder::Col::new(table_name, "blueprints_0"),
            active_blueprints: __sdk::__query_builder::Col::new(table_name, "active_blueprints"),

        }
    }
}

/// Indexed column accessor struct for the table `SoulPrivate`.
///
/// Provides typed access to indexed columns for query building.
pub struct SoulPrivateIxCols {
    pub card_id: __sdk::__query_builder::IxCol<SoulPrivate, u32>,
}

impl __sdk::__query_builder::HasIxCols for SoulPrivate {
    type IxCols = SoulPrivateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SoulPrivateIxCols {
            card_id: __sdk::__query_builder::IxCol::new(table_name, "card_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SoulPrivate {}

