// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::zone_type::Zone;

/// Table handle for the table `zones`.
///
/// Obtain a handle from the [`ZonesTableAccess::zones`] method on [`super::RemoteTables`],
/// like `ctx.db.zones()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.zones().on_insert(...)`.
pub struct ZonesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Zone>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `zones`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ZonesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ZonesTableHandle`], which mediates access to the table `zones`.
    fn zones(&self) -> ZonesTableHandle<'_>;
}

impl ZonesTableAccess for super::RemoteTables {
    fn zones(&self) -> ZonesTableHandle<'_> {
        ZonesTableHandle {
            imp: self.imp.get_table::<Zone>("zones"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ZonesInsertCallbackId(__sdk::CallbackId);
pub struct ZonesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ZonesTableHandle<'ctx> {
    type Row = Zone;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Zone> + '_ { self.imp.iter() }

    type InsertCallbackId = ZonesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZonesInsertCallbackId {
        ZonesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ZonesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ZonesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ZonesDeleteCallbackId {
        ZonesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ZonesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ZonesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ZonesTableHandle<'ctx> {
    type UpdateCallbackId = ZonesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ZonesUpdateCallbackId {
        ZonesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ZonesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `zones`,
        /// which allows point queries on the field of the same name
        /// via the [`ZonesValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.zones().valid_at().find(...)`.
        pub struct ZonesValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Zone, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> ZonesTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `zones`.
            pub fn valid_at(&self) -> ZonesValidAtUnique<'ctx> {
                ZonesValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> ZonesValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Zone> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Zone>("zones");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Zone>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Zone>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Zone`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait zonesQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Zone`.
            fn zones(&self) -> __sdk::__query_builder::Table<Zone>;
        }

        impl zonesQueryTableAccess for __sdk::QueryTableAccessor {
            fn zones(&self) -> __sdk::__query_builder::Table<Zone> {
                __sdk::__query_builder::Table::new("zones")
            }
        }

