// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Zone {
    pub valid_at: u64,
    pub zone_id: u32,
    pub macro_zone: u64,
    pub packed_definition: u8,
    pub owner_id: u32,
    pub t_0: u64,
    pub t_1: u64,
    pub t_2: u64,
    pub t_3: u64,
    pub t_4: u64,
    pub t_5: u64,
    pub t_6: u64,
    pub t_7: u64,
    pub t_8: u64,
    pub t_9: u64,
    pub t_10: u64,
    pub t_11: u64,
    pub t_12: u64,
    pub t_13: u64,
    pub t_14: u64,
    pub t_15: u64,
}


impl __sdk::InModule for Zone {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Zone`.
///
/// Provides typed access to columns for query building.
pub struct ZoneCols {
    pub valid_at: __sdk::__query_builder::Col<Zone, u64>,
    pub zone_id: __sdk::__query_builder::Col<Zone, u32>,
    pub macro_zone: __sdk::__query_builder::Col<Zone, u64>,
    pub packed_definition: __sdk::__query_builder::Col<Zone, u8>,
    pub owner_id: __sdk::__query_builder::Col<Zone, u32>,
    pub t_0: __sdk::__query_builder::Col<Zone, u64>,
    pub t_1: __sdk::__query_builder::Col<Zone, u64>,
    pub t_2: __sdk::__query_builder::Col<Zone, u64>,
    pub t_3: __sdk::__query_builder::Col<Zone, u64>,
    pub t_4: __sdk::__query_builder::Col<Zone, u64>,
    pub t_5: __sdk::__query_builder::Col<Zone, u64>,
    pub t_6: __sdk::__query_builder::Col<Zone, u64>,
    pub t_7: __sdk::__query_builder::Col<Zone, u64>,
    pub t_8: __sdk::__query_builder::Col<Zone, u64>,
    pub t_9: __sdk::__query_builder::Col<Zone, u64>,
    pub t_10: __sdk::__query_builder::Col<Zone, u64>,
    pub t_11: __sdk::__query_builder::Col<Zone, u64>,
    pub t_12: __sdk::__query_builder::Col<Zone, u64>,
    pub t_13: __sdk::__query_builder::Col<Zone, u64>,
    pub t_14: __sdk::__query_builder::Col<Zone, u64>,
    pub t_15: __sdk::__query_builder::Col<Zone, u64>,
}

impl __sdk::__query_builder::HasCols for Zone {
    type Cols = ZoneCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ZoneCols {
            valid_at: __sdk::__query_builder::Col::new(table_name, "valid_at"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            macro_zone: __sdk::__query_builder::Col::new(table_name, "macro_zone"),
            packed_definition: __sdk::__query_builder::Col::new(table_name, "packed_definition"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            t_0: __sdk::__query_builder::Col::new(table_name, "t_0"),
            t_1: __sdk::__query_builder::Col::new(table_name, "t_1"),
            t_2: __sdk::__query_builder::Col::new(table_name, "t_2"),
            t_3: __sdk::__query_builder::Col::new(table_name, "t_3"),
            t_4: __sdk::__query_builder::Col::new(table_name, "t_4"),
            t_5: __sdk::__query_builder::Col::new(table_name, "t_5"),
            t_6: __sdk::__query_builder::Col::new(table_name, "t_6"),
            t_7: __sdk::__query_builder::Col::new(table_name, "t_7"),
            t_8: __sdk::__query_builder::Col::new(table_name, "t_8"),
            t_9: __sdk::__query_builder::Col::new(table_name, "t_9"),
            t_10: __sdk::__query_builder::Col::new(table_name, "t_10"),
            t_11: __sdk::__query_builder::Col::new(table_name, "t_11"),
            t_12: __sdk::__query_builder::Col::new(table_name, "t_12"),
            t_13: __sdk::__query_builder::Col::new(table_name, "t_13"),
            t_14: __sdk::__query_builder::Col::new(table_name, "t_14"),
            t_15: __sdk::__query_builder::Col::new(table_name, "t_15"),

        }
    }
}

/// Indexed column accessor struct for the table `Zone`.
///
/// Provides typed access to indexed columns for query building.
pub struct ZoneIxCols {
    pub macro_zone: __sdk::__query_builder::IxCol<Zone, u64>,
    pub owner_id: __sdk::__query_builder::IxCol<Zone, u32>,
    pub valid_at: __sdk::__query_builder::IxCol<Zone, u64>,
    pub zone_id: __sdk::__query_builder::IxCol<Zone, u32>,
}

impl __sdk::__query_builder::HasIxCols for Zone {
    type IxCols = ZoneIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ZoneIxCols {
            macro_zone: __sdk::__query_builder::IxCol::new(table_name, "macro_zone"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            valid_at: __sdk::__query_builder::IxCol::new(table_name, "valid_at"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Zone {}

