// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};
use super::soul_type::Soul;

/// Table handle for the table `souls`.
///
/// Obtain a handle from the [`SoulsTableAccess::souls`] method on [`super::RemoteTables`],
/// like `ctx.db.souls()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.souls().on_insert(...)`.
pub struct SoulsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Soul>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `souls`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SoulsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SoulsTableHandle`], which mediates access to the table `souls`.
    fn souls(&self) -> SoulsTableHandle<'_>;
}

impl SoulsTableAccess for super::RemoteTables {
    fn souls(&self) -> SoulsTableHandle<'_> {
        SoulsTableHandle {
            imp: self.imp.get_table::<Soul>("souls"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SoulsInsertCallbackId(__sdk::CallbackId);
pub struct SoulsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SoulsTableHandle<'ctx> {
    type Row = Soul;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 { self.imp.count() }
    fn iter(&self) -> impl Iterator<Item = Soul> + '_ { self.imp.iter() }

    type InsertCallbackId = SoulsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SoulsInsertCallbackId {
        SoulsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SoulsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SoulsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SoulsDeleteCallbackId {
        SoulsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SoulsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SoulsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SoulsTableHandle<'ctx> {
    type UpdateCallbackId = SoulsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SoulsUpdateCallbackId {
        SoulsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SoulsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

        /// Access to the `valid_at` unique index on the table `souls`,
        /// which allows point queries on the field of the same name
        /// via the [`SoulsValidAtUnique::find`] method.
        ///
        /// Users are encouraged not to explicitly reference this type,
        /// but to directly chain method calls,
        /// like `ctx.db.souls().valid_at().find(...)`.
        pub struct SoulsValidAtUnique<'ctx> {
            imp: __sdk::UniqueConstraintHandle<Soul, u64>,
            phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
        }

        impl<'ctx> SoulsTableHandle<'ctx> {
            /// Get a handle on the `valid_at` unique index on the table `souls`.
            pub fn valid_at(&self) -> SoulsValidAtUnique<'ctx> {
                SoulsValidAtUnique {
                    imp: self.imp.get_unique_constraint::<u64>("valid_at"),
                    phantom: std::marker::PhantomData,
                }
            }
        }

        impl<'ctx> SoulsValidAtUnique<'ctx> {
            /// Find the subscribed row whose `valid_at` column value is equal to `col_val`,
            /// if such a row is present in the client cache.
            pub fn find(&self, col_val: &u64) -> Option<Soul> {
                self.imp.find(col_val)
            }
        }
        
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

    let _table = client_cache.get_or_make_table::<Soul>("souls");
    _table.add_unique_constraint::<u64>("valid_at", |row| &row.valid_at);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Soul>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<Soul>",
            "TableUpdate",
        ).with_cause(e).into()
    })
}

        #[allow(non_camel_case_types)]
        /// Extension trait for query builder access to the table `Soul`.
        ///
        /// Implemented for [`__sdk::QueryTableAccessor`].
        pub trait soulsQueryTableAccess {
            #[allow(non_snake_case)]
            /// Get a query builder for the table `Soul`.
            fn souls(&self) -> __sdk::__query_builder::Table<Soul>;
        }

        impl soulsQueryTableAccess for __sdk::QueryTableAccessor {
            fn souls(&self) -> __sdk::__query_builder::Table<Soul> {
                __sdk::__query_builder::Table::new("souls")
            }
        }

