// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Soul {
    pub valid_at: u64,
    pub data_shard: u16,
    pub card_id: u32,
    pub owner_id: u32,
    pub macro_zone: u64,
    pub micro_location: u32,
    pub stats: u32,
    pub fatigued: u32,
    pub injured: u32,
}


impl __sdk::InModule for Soul {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `Soul`.
///
/// Provides typed access to columns for query building.
pub struct SoulCols {
    pub valid_at: __sdk::__query_builder::Col<Soul, u64>,
    pub data_shard: __sdk::__query_builder::Col<Soul, u16>,
    pub card_id: __sdk::__query_builder::Col<Soul, u32>,
    pub owner_id: __sdk::__query_builder::Col<Soul, u32>,
    pub macro_zone: __sdk::__query_builder::Col<Soul, u64>,
    pub micro_location: __sdk::__query_builder::Col<Soul, u32>,
    pub stats: __sdk::__query_builder::Col<Soul, u32>,
    pub fatigued: __sdk::__query_builder::Col<Soul, u32>,
    pub injured: __sdk::__query_builder::Col<Soul, u32>,
}

impl __sdk::__query_builder::HasCols for Soul {
    type Cols = SoulCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SoulCols {
            valid_at: __sdk::__query_builder::Col::new(table_name, "valid_at"),
            data_shard: __sdk::__query_builder::Col::new(table_name, "data_shard"),
            card_id: __sdk::__query_builder::Col::new(table_name, "card_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            macro_zone: __sdk::__query_builder::Col::new(table_name, "macro_zone"),
            micro_location: __sdk::__query_builder::Col::new(table_name, "micro_location"),
            stats: __sdk::__query_builder::Col::new(table_name, "stats"),
            fatigued: __sdk::__query_builder::Col::new(table_name, "fatigued"),
            injured: __sdk::__query_builder::Col::new(table_name, "injured"),

        }
    }
}

/// Indexed column accessor struct for the table `Soul`.
///
/// Provides typed access to indexed columns for query building.
pub struct SoulIxCols {
    pub card_id: __sdk::__query_builder::IxCol<Soul, u32>,
    pub owner_id: __sdk::__query_builder::IxCol<Soul, u32>,
    pub valid_at: __sdk::__query_builder::IxCol<Soul, u64>,
}

impl __sdk::__query_builder::HasIxCols for Soul {
    type IxCols = SoulIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SoulIxCols {
            card_id: __sdk::__query_builder::IxCol::new(table_name, "card_id"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
            valid_at: __sdk::__query_builder::IxCol::new(table_name, "valid_at"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Soul {}

