// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RegionShard {
    pub macro_region: u64,
    pub data_shard: u16,
}


impl __sdk::InModule for RegionShard {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `RegionShard`.
///
/// Provides typed access to columns for query building.
pub struct RegionShardCols {
    pub macro_region: __sdk::__query_builder::Col<RegionShard, u64>,
    pub data_shard: __sdk::__query_builder::Col<RegionShard, u16>,
}

impl __sdk::__query_builder::HasCols for RegionShard {
    type Cols = RegionShardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RegionShardCols {
            macro_region: __sdk::__query_builder::Col::new(table_name, "macro_region"),
            data_shard: __sdk::__query_builder::Col::new(table_name, "data_shard"),

        }
    }
}

/// Indexed column accessor struct for the table `RegionShard`.
///
/// Provides typed access to indexed columns for query building.
pub struct RegionShardIxCols {
    pub macro_region: __sdk::__query_builder::IxCol<RegionShard, u64>,
}

impl __sdk::__query_builder::HasIxCols for RegionShard {
    type IxCols = RegionShardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RegionShardIxCols {
            macro_region: __sdk::__query_builder::IxCol::new(table_name, "macro_region"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RegionShard {}

