// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AcquireTileLeaseArgs {
    pub surface: u8,
    pub macro_zone: u64,
    pub q: u8,
    pub r: u8,
    pub kind: u8,
    pub acquire_ms: u64,
    pub release_ms: u64,
}

impl From<AcquireTileLeaseArgs> for super::Reducer {
    fn from(args: AcquireTileLeaseArgs) -> Self {
        Self::AcquireTileLease {
            surface: args.surface,
            macro_zone: args.macro_zone,
            q: args.q,
            r: args.r,
            kind: args.kind,
            acquire_ms: args.acquire_ms,
            release_ms: args.release_ms,
}
}
}

impl __sdk::InModule for AcquireTileLeaseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `acquire_tile_lease`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait acquire_tile_lease {
    /// Request that the remote module invoke the reducer `acquire_tile_lease` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`acquire_tile_lease:acquire_tile_lease_then`] to run a callback after the reducer completes.
    fn acquire_tile_lease(&self, surface: u8,
macro_zone: u64,
q: u8,
r: u8,
kind: u8,
acquire_ms: u64,
release_ms: u64,
) -> __sdk::Result<()> {
        self.acquire_tile_lease_then(surface, macro_zone, q, r, kind, acquire_ms, release_ms,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `acquire_tile_lease` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn acquire_tile_lease_then(
        &self,
        surface: u8,
macro_zone: u64,
q: u8,
r: u8,
kind: u8,
acquire_ms: u64,
release_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl acquire_tile_lease for super::RemoteReducers {
    fn acquire_tile_lease_then(
        &self,
        surface: u8,
macro_zone: u64,
q: u8,
r: u8,
kind: u8,
acquire_ms: u64,
release_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AcquireTileLeaseArgs { surface, macro_zone, q, r, kind, acquire_ms, release_ms,  }, callback)
    }
}

