// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CardShard {
    pub valid_at: u64,
    pub data_shard: u16,
    pub ref_count: u32,
}


impl __sdk::InModule for CardShard {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `CardShard`.
///
/// Provides typed access to columns for query building.
pub struct CardShardCols {
    pub valid_at: __sdk::__query_builder::Col<CardShard, u64>,
    pub data_shard: __sdk::__query_builder::Col<CardShard, u16>,
    pub ref_count: __sdk::__query_builder::Col<CardShard, u32>,
}

impl __sdk::__query_builder::HasCols for CardShard {
    type Cols = CardShardCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CardShardCols {
            valid_at: __sdk::__query_builder::Col::new(table_name, "valid_at"),
            data_shard: __sdk::__query_builder::Col::new(table_name, "data_shard"),
            ref_count: __sdk::__query_builder::Col::new(table_name, "ref_count"),

        }
    }
}

/// Indexed column accessor struct for the table `CardShard`.
///
/// Provides typed access to indexed columns for query building.
pub struct CardShardIxCols {
    pub data_shard: __sdk::__query_builder::IxCol<CardShard, u16>,
    pub valid_at: __sdk::__query_builder::IxCol<CardShard, u64>,
}

impl __sdk::__query_builder::HasIxCols for CardShard {
    type IxCols = CardShardIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CardShardIxCols {
            data_shard: __sdk::__query_builder::IxCol::new(table_name, "data_shard"),
            valid_at: __sdk::__query_builder::IxCol::new(table_name, "valid_at"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CardShard {}

