// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GenerateForestTerrainArgs {
    pub seed: u64,
    pub radius: i16,
}

impl From<GenerateForestTerrainArgs> for super::Reducer {
    fn from(args: GenerateForestTerrainArgs) -> Self {
        Self::GenerateForestTerrain {
            seed: args.seed,
            radius: args.radius,
}
}
}

impl __sdk::InModule for GenerateForestTerrainArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `generate_forest_terrain`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait generate_forest_terrain {
    /// Request that the remote module invoke the reducer `generate_forest_terrain` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`generate_forest_terrain:generate_forest_terrain_then`] to run a callback after the reducer completes.
    fn generate_forest_terrain(&self, seed: u64,
radius: i16,
) -> __sdk::Result<()> {
        self.generate_forest_terrain_then(seed, radius,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `generate_forest_terrain` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn generate_forest_terrain_then(
        &self,
        seed: u64,
radius: i16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl generate_forest_terrain for super::RemoteReducers {
    fn generate_forest_terrain_then(
        &self,
        seed: u64,
radius: i16,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(GenerateForestTerrainArgs { seed, radius,  }, callback)
    }
}

