// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetTileArgs {
    pub zone_id: u32,
    pub time_ms: u64,
    pub row: u8,
    pub col: u8,
    pub def_id: u16,
    pub stock_0: u8,
    pub stock_1: u8,
}

impl From<SetTileArgs> for super::Reducer {
    fn from(args: SetTileArgs) -> Self {
        Self::SetTile {
            zone_id: args.zone_id,
            time_ms: args.time_ms,
            row: args.row,
            col: args.col,
            def_id: args.def_id,
            stock_0: args.stock_0,
            stock_1: args.stock_1,
}
}
}

impl __sdk::InModule for SetTileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_tile`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_tile {
    /// Request that the remote module invoke the reducer `set_tile` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_tile:set_tile_then`] to run a callback after the reducer completes.
    fn set_tile(&self, zone_id: u32,
time_ms: u64,
row: u8,
col: u8,
def_id: u16,
stock_0: u8,
stock_1: u8,
) -> __sdk::Result<()> {
        self.set_tile_then(zone_id, time_ms, row, col, def_id, stock_0, stock_1,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_tile` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_tile_then(
        &self,
        zone_id: u32,
time_ms: u64,
row: u8,
col: u8,
def_id: u16,
stock_0: u8,
stock_1: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_tile for super::RemoteReducers {
    fn set_tile_then(
        &self,
        zone_id: u32,
time_ms: u64,
row: u8,
col: u8,
def_id: u16,
stock_0: u8,
stock_1: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetTileArgs { zone_id, time_ms, row, col, def_id, stock_0, stock_1,  }, callback)
    }
}

