// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetTileStockArgs {
    pub time_ms: u64,
    pub surface: u8,
    pub macro_zone: u64,
    pub q: u8,
    pub r: u8,
    pub slot: u8,
    pub op: u8,
    pub delta: u8,
}

impl From<SetTileStockArgs> for super::Reducer {
    fn from(args: SetTileStockArgs) -> Self {
        Self::SetTileStock {
            time_ms: args.time_ms,
            surface: args.surface,
            macro_zone: args.macro_zone,
            q: args.q,
            r: args.r,
            slot: args.slot,
            op: args.op,
            delta: args.delta,
}
}
}

impl __sdk::InModule for SetTileStockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_tile_stock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_tile_stock {
    /// Request that the remote module invoke the reducer `set_tile_stock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_tile_stock:set_tile_stock_then`] to run a callback after the reducer completes.
    fn set_tile_stock(&self, time_ms: u64,
surface: u8,
macro_zone: u64,
q: u8,
r: u8,
slot: u8,
op: u8,
delta: u8,
) -> __sdk::Result<()> {
        self.set_tile_stock_then(time_ms, surface, macro_zone, q, r, slot, op, delta,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_tile_stock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_tile_stock_then(
        &self,
        time_ms: u64,
surface: u8,
macro_zone: u64,
q: u8,
r: u8,
slot: u8,
op: u8,
delta: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_tile_stock for super::RemoteReducers {
    fn set_tile_stock_then(
        &self,
        time_ms: u64,
surface: u8,
macro_zone: u64,
q: u8,
r: u8,
slot: u8,
op: u8,
delta: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SetTileStockArgs { time_ms, surface, macro_zone, q, r, slot, op, delta,  }, callback)
    }
}

