// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AcquireHoldArgs {
    pub card_id: u32,
    pub time_ms: u64,
    pub kind: u8,
}

impl From<AcquireHoldArgs> for super::Reducer {
    fn from(args: AcquireHoldArgs) -> Self {
        Self::AcquireHold {
            card_id: args.card_id,
            time_ms: args.time_ms,
            kind: args.kind,
}
}
}

impl __sdk::InModule for AcquireHoldArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `acquire_hold`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait acquire_hold {
    /// Request that the remote module invoke the reducer `acquire_hold` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`acquire_hold:acquire_hold_then`] to run a callback after the reducer completes.
    fn acquire_hold(&self, card_id: u32,
time_ms: u64,
kind: u8,
) -> __sdk::Result<()> {
        self.acquire_hold_then(card_id, time_ms, kind,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `acquire_hold` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn acquire_hold_then(
        &self,
        card_id: u32,
time_ms: u64,
kind: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl acquire_hold for super::RemoteReducers {
    fn acquire_hold_then(
        &self,
        card_id: u32,
time_ms: u64,
kind: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(AcquireHoldArgs { card_id, time_ms, kind,  }, callback)
    }
}

