// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimPendingArgs {
    pub recipe_id: u16,
    pub root: u32,
    pub bindings: Vec::<Vec::<u32>>,
    pub completion_ms: u64,
}

impl From<ClaimPendingArgs> for super::Reducer {
    fn from(args: ClaimPendingArgs) -> Self {
        Self::ClaimPending {
            recipe_id: args.recipe_id,
            root: args.root,
            bindings: args.bindings,
            completion_ms: args.completion_ms,
}
}
}

impl __sdk::InModule for ClaimPendingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_pending`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_pending {
    /// Request that the remote module invoke the reducer `claim_pending` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_pending:claim_pending_then`] to run a callback after the reducer completes.
    fn claim_pending(&self, recipe_id: u16,
root: u32,
bindings: Vec::<Vec::<u32>>,
completion_ms: u64,
) -> __sdk::Result<()> {
        self.claim_pending_then(recipe_id, root, bindings, completion_ms,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_pending` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_pending_then(
        &self,
        recipe_id: u16,
root: u32,
bindings: Vec::<Vec::<u32>>,
completion_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_pending for super::RemoteReducers {
    fn claim_pending_then(
        &self,
        recipe_id: u16,
root: u32,
bindings: Vec::<Vec::<u32>>,
completion_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ClaimPendingArgs { recipe_id, root, bindings, completion_ms,  }, callback)
    }
}

