// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCardArgs {
    pub time_ms: u64,
    pub def_key: String,
    pub surface: u8,
    pub macro_zone: u64,
    pub owner_id: u32,
}

impl From<CreateCardArgs> for super::Reducer {
    fn from(args: CreateCardArgs) -> Self {
        Self::CreateCard {
            time_ms: args.time_ms,
            def_key: args.def_key,
            surface: args.surface,
            macro_zone: args.macro_zone,
            owner_id: args.owner_id,
}
}
}

impl __sdk::InModule for CreateCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_card {
    /// Request that the remote module invoke the reducer `create_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_card:create_card_then`] to run a callback after the reducer completes.
    fn create_card(&self, time_ms: u64,
def_key: String,
surface: u8,
macro_zone: u64,
owner_id: u32,
) -> __sdk::Result<()> {
        self.create_card_then(time_ms, def_key, surface, macro_zone, owner_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_card_then(
        &self,
        time_ms: u64,
def_key: String,
surface: u8,
macro_zone: u64,
owner_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_card for super::RemoteReducers {
    fn create_card_then(
        &self,
        time_ms: u64,
def_key: String,
surface: u8,
macro_zone: u64,
owner_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(CreateCardArgs { time_ms, def_key, surface, macro_zone, owner_id,  }, callback)
    }
}

