// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit aa73d1c35b4b346b98eeba10a3d756b4ae72162f).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};

pub mod card_type;
pub mod card_id_counter_type;
pub mod gc_schedule_type;
pub mod pending_action_type;
pub mod placement_type;
pub mod sequence_counter_type;
pub mod soul_type;
pub mod soul_private_type;
pub mod tile_point_type;
pub mod acquire_hold_reducer;
pub mod add_card_reducer;
pub mod claim_pending_reducer;
pub mod create_card_reducer;
pub mod destroy_card_reducer;
pub mod finalize_card_reducer;
pub mod move_card_reducer;
pub mod move_soul_reducer;
pub mod place_card_reducer;
pub mod release_hold_reducer;
pub mod release_pending_reducer;
pub mod request_blueprint_reducer;
pub mod spawn_soul_reducer;
pub mod stack_card_reducer;
pub mod unlock_blueprint_reducer;
pub mod cards_table;
pub mod soul_privates_table;
pub mod souls_table;

pub use card_type::Card;
pub use card_id_counter_type::CardIdCounter;
pub use gc_schedule_type::GcSchedule;
pub use pending_action_type::PendingAction;
pub use placement_type::Placement;
pub use sequence_counter_type::SequenceCounter;
pub use soul_type::Soul;
pub use soul_private_type::SoulPrivate;
pub use tile_point_type::TilePoint;
pub use cards_table::*;
pub use soul_privates_table::*;
pub use souls_table::*;
pub use acquire_hold_reducer::acquire_hold;
pub use add_card_reducer::add_card;
pub use claim_pending_reducer::claim_pending;
pub use create_card_reducer::create_card;
pub use destroy_card_reducer::destroy_card;
pub use finalize_card_reducer::finalize_card;
pub use move_card_reducer::move_card;
pub use move_soul_reducer::move_soul;
pub use place_card_reducer::place_card;
pub use release_hold_reducer::release_hold;
pub use release_pending_reducer::release_pending;
pub use request_blueprint_reducer::request_blueprint;
pub use spawn_soul_reducer::spawn_soul;
pub use stack_card_reducer::stack_card;
pub use unlock_blueprint_reducer::unlock_blueprint;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
        AcquireHold {
        card_id: u32,
        time_ms: u64,
        kind: u8,
}    ,
    AddCard {
        client_time_ms: u64,
        soul_card_id: u32,
        card_key: String,
}    ,
    ClaimPending {
        recipe_id: u16,
        root: u32,
        bindings: Vec::<Vec::<u32>>,
        completion_ms: u64,
}    ,
    CreateCard {
        time_ms: u64,
        def_key: String,
        surface: u8,
        macro_zone: u64,
        owner_id: u32,
}    ,
    DestroyCard {
        card_id: u32,
        time_ms: u64,
}    ,
    FinalizeCard {
        card_id: u32,
        time_ms: u64,
        progress_style: u8,
}    ,
    MoveCard {
        card_id: u32,
        time_ms: u64,
        surface: u8,
        macro_zone: u64,
        micro_location: u32,
}    ,
    MoveSoul {
        client_time_ms: u64,
        caller_player_id: u32,
        soul_id: u32,
        path: Vec::<TilePoint>,
}    ,
    PlaceCard {
        client_time_ms: u64,
        caller_player_id: u32,
        card_id: u32,
        placement: Placement,
}    ,
    ReleaseHold {
        card_id: u32,
        time_ms: u64,
        kind: u8,
}    ,
    ReleasePending {
        recipe_id: u16,
        root: u32,
        bindings: Vec::<Vec::<u32>>,
}    ,
    RequestBlueprint {
        client_time_ms: u64,
        caller_player_id: u32,
        soul_card_id: u32,
        blueprint_id: u16,
        surface: u8,
        macro_zone: u64,
        micro_location: u32,
}    ,
    SpawnSoul {
        client_time_ms: u64,
        player_id: u32,
        soul_index: u32,
}    ,
    StackCard {
        card_id: u32,
        time_ms: u64,
        surface: u8,
        macro_zone: u64,
        root: u32,
        branch: u8,
        index: u8,
}    ,
    UnlockBlueprint {
        target_card_id: u32,
        blueprint_key: String,
}    ,
}


impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
                        Reducer::AcquireHold { .. } => "acquire_hold",
            Reducer::AddCard { .. } => "add_card",
            Reducer::ClaimPending { .. } => "claim_pending",
            Reducer::CreateCard { .. } => "create_card",
            Reducer::DestroyCard { .. } => "destroy_card",
            Reducer::FinalizeCard { .. } => "finalize_card",
            Reducer::MoveCard { .. } => "move_card",
            Reducer::MoveSoul { .. } => "move_soul",
            Reducer::PlaceCard { .. } => "place_card",
            Reducer::ReleaseHold { .. } => "release_hold",
            Reducer::ReleasePending { .. } => "release_pending",
            Reducer::RequestBlueprint { .. } => "request_blueprint",
            Reducer::SpawnSoul { .. } => "spawn_soul",
            Reducer::StackCard { .. } => "stack_card",
            Reducer::UnlockBlueprint { .. } => "unlock_blueprint",
            _ => unreachable!(),
}
}
    #[allow(clippy::clone_on_copy)]
fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AcquireHold{
                card_id,
                time_ms,
                kind,
}             => __sats::bsatn::to_vec(&acquire_hold_reducer::AcquireHoldArgs {
                card_id: card_id.clone(),
                time_ms: time_ms.clone(),
                kind: kind.clone(),
}),
            Reducer::AddCard{
                client_time_ms,
                soul_card_id,
                card_key,
}             => __sats::bsatn::to_vec(&add_card_reducer::AddCardArgs {
                client_time_ms: client_time_ms.clone(),
                soul_card_id: soul_card_id.clone(),
                card_key: card_key.clone(),
}),
            Reducer::ClaimPending{
                recipe_id,
                root,
                bindings,
                completion_ms,
}             => __sats::bsatn::to_vec(&claim_pending_reducer::ClaimPendingArgs {
                recipe_id: recipe_id.clone(),
                root: root.clone(),
                bindings: bindings.clone(),
                completion_ms: completion_ms.clone(),
}),
            Reducer::CreateCard{
                time_ms,
                def_key,
                surface,
                macro_zone,
                owner_id,
}             => __sats::bsatn::to_vec(&create_card_reducer::CreateCardArgs {
                time_ms: time_ms.clone(),
                def_key: def_key.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                owner_id: owner_id.clone(),
}),
            Reducer::DestroyCard{
                card_id,
                time_ms,
}             => __sats::bsatn::to_vec(&destroy_card_reducer::DestroyCardArgs {
                card_id: card_id.clone(),
                time_ms: time_ms.clone(),
}),
            Reducer::FinalizeCard{
                card_id,
                time_ms,
                progress_style,
}             => __sats::bsatn::to_vec(&finalize_card_reducer::FinalizeCardArgs {
                card_id: card_id.clone(),
                time_ms: time_ms.clone(),
                progress_style: progress_style.clone(),
}),
            Reducer::MoveCard{
                card_id,
                time_ms,
                surface,
                macro_zone,
                micro_location,
}             => __sats::bsatn::to_vec(&move_card_reducer::MoveCardArgs {
                card_id: card_id.clone(),
                time_ms: time_ms.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                micro_location: micro_location.clone(),
}),
            Reducer::MoveSoul{
                client_time_ms,
                caller_player_id,
                soul_id,
                path,
}             => __sats::bsatn::to_vec(&move_soul_reducer::MoveSoulArgs {
                client_time_ms: client_time_ms.clone(),
                caller_player_id: caller_player_id.clone(),
                soul_id: soul_id.clone(),
                path: path.clone(),
}),
            Reducer::PlaceCard{
                client_time_ms,
                caller_player_id,
                card_id,
                placement,
}             => __sats::bsatn::to_vec(&place_card_reducer::PlaceCardArgs {
                client_time_ms: client_time_ms.clone(),
                caller_player_id: caller_player_id.clone(),
                card_id: card_id.clone(),
                placement: placement.clone(),
}),
            Reducer::ReleaseHold{
                card_id,
                time_ms,
                kind,
}             => __sats::bsatn::to_vec(&release_hold_reducer::ReleaseHoldArgs {
                card_id: card_id.clone(),
                time_ms: time_ms.clone(),
                kind: kind.clone(),
}),
            Reducer::ReleasePending{
                recipe_id,
                root,
                bindings,
}             => __sats::bsatn::to_vec(&release_pending_reducer::ReleasePendingArgs {
                recipe_id: recipe_id.clone(),
                root: root.clone(),
                bindings: bindings.clone(),
}),
            Reducer::RequestBlueprint{
                client_time_ms,
                caller_player_id,
                soul_card_id,
                blueprint_id,
                surface,
                macro_zone,
                micro_location,
}             => __sats::bsatn::to_vec(&request_blueprint_reducer::RequestBlueprintArgs {
                client_time_ms: client_time_ms.clone(),
                caller_player_id: caller_player_id.clone(),
                soul_card_id: soul_card_id.clone(),
                blueprint_id: blueprint_id.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                micro_location: micro_location.clone(),
}),
            Reducer::SpawnSoul{
                client_time_ms,
                player_id,
                soul_index,
}             => __sats::bsatn::to_vec(&spawn_soul_reducer::SpawnSoulArgs {
                client_time_ms: client_time_ms.clone(),
                player_id: player_id.clone(),
                soul_index: soul_index.clone(),
}),
            Reducer::StackCard{
                card_id,
                time_ms,
                surface,
                macro_zone,
                root,
                branch,
                index,
}             => __sats::bsatn::to_vec(&stack_card_reducer::StackCardArgs {
                card_id: card_id.clone(),
                time_ms: time_ms.clone(),
                surface: surface.clone(),
                macro_zone: macro_zone.clone(),
                root: root.clone(),
                branch: branch.clone(),
                index: index.clone(),
}),
            Reducer::UnlockBlueprint{
                target_card_id,
                blueprint_key,
}             => __sats::bsatn::to_vec(&unlock_blueprint_reducer::UnlockBlueprintArgs {
                target_card_id: target_card_id.clone(),
                blueprint_key: blueprint_key.clone(),
}),
            _ => unreachable!(),
}
}
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
        cards: __sdk::TableUpdate<Card>,
    soul_privates: __sdk::TableUpdate<SoulPrivate>,
    souls: __sdk::TableUpdate<Soul>,
}


impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {

        "cards" => db_update.cards.append(cards_table::parse_table_update(table_update)?),
    "soul_privates" => db_update.soul_privates.append(soul_privates_table::parse_table_update(table_update)?),
    "souls" => db_update.souls.append(souls_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    ).into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(&self, cache: &mut __sdk::ClientCache<RemoteModule>) -> AppliedDiff<'_> {
                    let mut diff = AppliedDiff::default();
                
                diff.cards = cache.apply_diff_to_table::<Card>("cards", &self.cards).with_updates_by_pk(|row| &row.valid_at);
        diff.soul_privates = cache.apply_diff_to_table::<SoulPrivate>("soul_privates", &self.soul_privates).with_updates_by_pk(|row| &row.card_id);
        diff.souls = cache.apply_diff_to_table::<Soul>("souls", &self.souls).with_updates_by_pk(|row| &row.valid_at);

                    diff
                }
fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "cards" => db_update.cards.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "soul_privates" => db_update.soul_privates.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "souls" => db_update.souls.append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
                let mut db_update = DbUpdate::default();
for table_rows in raw.tables {
            match &table_rows.table[..] {
                                "cards" => db_update.cards.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "soul_privates" => db_update.soul_privates.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "souls" => db_update.souls.append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => { return Err(__sdk::InternalError::unknown_name("table", unknown, "QueryRows").into()); }
}}        Ok(db_update)
}
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
        cards: __sdk::TableAppliedDiff<'r, Card>,
    soul_privates: __sdk::TableAppliedDiff<'r, SoulPrivate>,
    souls: __sdk::TableAppliedDiff<'r, Soul>,
    __unused: std::marker::PhantomData<&'r ()>,
}


impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(&self, event: &EventContext, callbacks: &mut __sdk::DbCallbacks<RemoteModule>) {
                callbacks.invoke_table_row_callbacks::<Card>("cards", &self.cards, event);
        callbacks.invoke_table_row_callbacks::<SoulPrivate>("soul_privates", &self.soul_privates, event);
        callbacks.invoke_table_row_callbacks::<Soul>("souls", &self.souls, event);
}
}


#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(target_arch = "wasm32", doc = "- [`DbConnection::run_background_task`].")]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(not(target_arch =  "wasm32"), doc = "- [`DbConnection::advance_one_message_blocking`].")]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }

}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
> {}
impl<Ctx: __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>> RemoteDbContext for Ctx {}


/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
                cards_table::register_table(client_cache);
        soul_privates_table::register_table(client_cache);
        souls_table::register_table(client_cache);
}
const ALL_TABLE_NAMES: &'static [&'static str] = &[
                "cards",
        "soul_privates",
        "souls",
];
}
