// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveCardArgs {
    pub card_id: u32,
    pub time_ms: u64,
    pub surface: u8,
    pub macro_zone: u64,
    pub micro_location: u32,
}

impl From<MoveCardArgs> for super::Reducer {
    fn from(args: MoveCardArgs) -> Self {
        Self::MoveCard {
            card_id: args.card_id,
            time_ms: args.time_ms,
            surface: args.surface,
            macro_zone: args.macro_zone,
            micro_location: args.micro_location,
}
}
}

impl __sdk::InModule for MoveCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_card {
    /// Request that the remote module invoke the reducer `move_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_card:move_card_then`] to run a callback after the reducer completes.
    fn move_card(&self, card_id: u32,
time_ms: u64,
surface: u8,
macro_zone: u64,
micro_location: u32,
) -> __sdk::Result<()> {
        self.move_card_then(card_id, time_ms, surface, macro_zone, micro_location,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_card_then(
        &self,
        card_id: u32,
time_ms: u64,
surface: u8,
macro_zone: u64,
micro_location: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_card for super::RemoteReducers {
    fn move_card_then(
        &self,
        card_id: u32,
time_ms: u64,
surface: u8,
macro_zone: u64,
micro_location: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(MoveCardArgs { card_id, time_ms, surface, macro_zone, micro_location,  }, callback)
    }
}

