// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PendingAction {
    pub dedup_key: u64,
    pub completion_ms: u64,
}


impl __sdk::InModule for PendingAction {
    type Module = super::RemoteModule;
}


/// Column accessor struct for the table `PendingAction`.
///
/// Provides typed access to columns for query building.
pub struct PendingActionCols {
    pub dedup_key: __sdk::__query_builder::Col<PendingAction, u64>,
    pub completion_ms: __sdk::__query_builder::Col<PendingAction, u64>,
}

impl __sdk::__query_builder::HasCols for PendingAction {
    type Cols = PendingActionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PendingActionCols {
            dedup_key: __sdk::__query_builder::Col::new(table_name, "dedup_key"),
            completion_ms: __sdk::__query_builder::Col::new(table_name, "completion_ms"),

        }
    }
}

/// Indexed column accessor struct for the table `PendingAction`.
///
/// Provides typed access to indexed columns for query building.
pub struct PendingActionIxCols {
    pub dedup_key: __sdk::__query_builder::IxCol<PendingAction, u64>,
}

impl __sdk::__query_builder::HasIxCols for PendingAction {
    type IxCols = PendingActionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PendingActionIxCols {
            dedup_key: __sdk::__query_builder::IxCol::new(table_name, "dedup_key"),

        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PendingAction {}

