// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Placement {
    pub kind: u8,
    pub parent_id: u32,
    pub direction: u8,
    pub surface: u8,
    pub macro_zone: u64,
    pub q: u8,
    pub r: u8,
    pub xy: u32,
}


impl __sdk::InModule for Placement {
    type Module = super::RemoteModule;
}

