// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReleasePendingArgs {
    pub recipe_id: u16,
    pub root: u32,
    pub bindings: Vec::<Vec::<u32>>,
}

impl From<ReleasePendingArgs> for super::Reducer {
    fn from(args: ReleasePendingArgs) -> Self {
        Self::ReleasePending {
            recipe_id: args.recipe_id,
            root: args.root,
            bindings: args.bindings,
}
}
}

impl __sdk::InModule for ReleasePendingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `release_pending`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait release_pending {
    /// Request that the remote module invoke the reducer `release_pending` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`release_pending:release_pending_then`] to run a callback after the reducer completes.
    fn release_pending(&self, recipe_id: u16,
root: u32,
bindings: Vec::<Vec::<u32>>,
) -> __sdk::Result<()> {
        self.release_pending_then(recipe_id, root, bindings,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `release_pending` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn release_pending_then(
        &self,
        recipe_id: u16,
root: u32,
bindings: Vec::<Vec::<u32>>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl release_pending for super::RemoteReducers {
    fn release_pending_then(
        &self,
        recipe_id: u16,
root: u32,
bindings: Vec::<Vec::<u32>>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ReleasePendingArgs { recipe_id, root, bindings,  }, callback)
    }
}

