// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnSoulArgs {
    pub client_time_ms: u64,
    pub player_id: u32,
}

impl From<SpawnSoulArgs> for super::Reducer {
    fn from(args: SpawnSoulArgs) -> Self {
        Self::SpawnSoul {
            client_time_ms: args.client_time_ms,
            player_id: args.player_id,
}
}
}

impl __sdk::InModule for SpawnSoulArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_soul`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_soul {
    /// Request that the remote module invoke the reducer `spawn_soul` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_soul:spawn_soul_then`] to run a callback after the reducer completes.
    fn spawn_soul(&self, client_time_ms: u64,
player_id: u32,
) -> __sdk::Result<()> {
        self.spawn_soul_then(client_time_ms, player_id,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_soul` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_soul_then(
        &self,
        client_time_ms: u64,
player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_soul for super::RemoteReducers {
    fn spawn_soul_then(
        &self,
        client_time_ms: u64,
player_id: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(SpawnSoulArgs { client_time_ms, player_id,  }, callback)
    }
}

