// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StackCardArgs {
    pub card_id: u32,
    pub time_ms: u64,
    pub surface: u8,
    pub macro_zone: u64,
    pub root: u32,
    pub branch: u8,
    pub index: u8,
}

impl From<StackCardArgs> for super::Reducer {
    fn from(args: StackCardArgs) -> Self {
        Self::StackCard {
            card_id: args.card_id,
            time_ms: args.time_ms,
            surface: args.surface,
            macro_zone: args.macro_zone,
            root: args.root,
            branch: args.branch,
            index: args.index,
}
}
}

impl __sdk::InModule for StackCardArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stack_card`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stack_card {
    /// Request that the remote module invoke the reducer `stack_card` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stack_card:stack_card_then`] to run a callback after the reducer completes.
    fn stack_card(&self, card_id: u32,
time_ms: u64,
surface: u8,
macro_zone: u64,
root: u32,
branch: u8,
index: u8,
) -> __sdk::Result<()> {
        self.stack_card_then(card_id, time_ms, surface, macro_zone, root, branch, index,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stack_card` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stack_card_then(
        &self,
        card_id: u32,
time_ms: u64,
surface: u8,
macro_zone: u64,
root: u32,
branch: u8,
index: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stack_card for super::RemoteReducers {
    fn stack_card_then(
        &self,
        card_id: u32,
time_ms: u64,
surface: u8,
macro_zone: u64,
root: u32,
branch: u8,
index: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(StackCardArgs { card_id, time_ms, surface, macro_zone, root, branch, index,  }, callback)
    }
}

