// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnlockBlueprintArgs {
    pub target_card_id: u32,
    pub blueprint_key: String,
}

impl From<UnlockBlueprintArgs> for super::Reducer {
    fn from(args: UnlockBlueprintArgs) -> Self {
        Self::UnlockBlueprint {
            target_card_id: args.target_card_id,
            blueprint_key: args.blueprint_key,
}
}
}

impl __sdk::InModule for UnlockBlueprintArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unlock_blueprint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unlock_blueprint {
    /// Request that the remote module invoke the reducer `unlock_blueprint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unlock_blueprint:unlock_blueprint_then`] to run a callback after the reducer completes.
    fn unlock_blueprint(&self, target_card_id: u32,
blueprint_key: String,
) -> __sdk::Result<()> {
        self.unlock_blueprint_then(target_card_id, blueprint_key,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unlock_blueprint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unlock_blueprint_then(
        &self,
        target_card_id: u32,
blueprint_key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unlock_blueprint for super::RemoteReducers {
    fn unlock_blueprint_then(
        &self,
        target_card_id: u32,
blueprint_key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(UnlockBlueprintArgs { target_card_id, blueprint_key,  }, callback)
    }
}

